/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 523e96d1af10
 */

import * as z from "zod/v3";
import { GleanBaseError } from "./gleanbaseerror.js";

/**
 * Error response for custom metadata operations
 */
export type ErrorInfoResponseData = {
  /**
   * Error message describing what went wrong
   */
  error: string;
  /**
   * Additional details about the error
   */
  message?: string | undefined;
};

/**
 * Error response for custom metadata operations
 */
export class ErrorInfoResponse extends GleanBaseError {
  /**
   * Error message describing what went wrong
   */
  error: string;

  /** The original data that was passed to this error instance. */
  data$: ErrorInfoResponseData;

  constructor(
    err: ErrorInfoResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ErrorInfoResponse";
  }
}

/** @internal */
export const ErrorInfoResponse$inboundSchema: z.ZodType<
  ErrorInfoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
  message: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ErrorInfoResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
