// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5bebaf9b24ce

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPostAPIAgentsAgentIDRuns(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "platform-agents-create-run[0]":
			dir.HandlerFunc("platform-agents-create-run", testPlatformAgentsCreateRunPlatformAgentsCreateRun0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testPlatformAgentsCreateRunPlatformAgentsCreateRun0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, "Bearer"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json;q=1", "text/event-stream;q=0"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.PlatformAgentRunWaitResponse = &components.PlatformAgentRunWaitResponse{
		Run: &components.PlatformAgentRun{
			AgentID: "<id>",
			Messages: []components.PlatformMessage{
				components.PlatformMessage{
					Role:    components.PlatformMessageRoleUser,
					Content: []components.PlatformMessageTextBlock{},
				},
			},
			Status: components.PlatformAgentExecutionStatusError,
		},
		Messages: []components.PlatformMessage{
			components.PlatformMessage{
				Role:    components.PlatformMessageRoleUser,
				Content: []components.PlatformMessageTextBlock{},
			},
		},
		RequestID: "<id>",
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
