/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5dc1c978699a
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { adminUsageListLimitIncreaseRequests } from "../funcs/adminUsageListLimitIncreaseRequests.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
export type AdminUsageListLimitIncreaseRequestsQueryData =
  components.PlatformRequestListResponseUnion;

export function prefetchAdminUsageListLimitIncreaseRequests(
  queryClient: QueryClient,
  client$: GleanCore,
  pageSize?: number | undefined,
  cursor?: string | undefined,
  filters?: Array<components.PlatformRequestFilter> | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildAdminUsageListLimitIncreaseRequestsQuery(
      client$,
      pageSize,
      cursor,
      filters,
      options,
    ),
  });
}

export function buildAdminUsageListLimitIncreaseRequestsQuery(
  client$: GleanCore,
  pageSize?: number | undefined,
  cursor?: string | undefined,
  filters?: Array<components.PlatformRequestFilter> | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<AdminUsageListLimitIncreaseRequestsQueryData>;
} {
  return {
    queryKey: queryKeyAdminUsageListLimitIncreaseRequests({
      pageSize,
      cursor,
      filters,
    }),
    queryFn: async function adminUsageListLimitIncreaseRequestsQueryFn(
      ctx,
    ): Promise<AdminUsageListLimitIncreaseRequestsQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(adminUsageListLimitIncreaseRequests(
        client$,
        pageSize,
        cursor,
        filters,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyAdminUsageListLimitIncreaseRequests(
  parameters: {
    pageSize?: number | undefined;
    cursor?: string | undefined;
    filters?: Array<components.PlatformRequestFilter> | undefined;
  },
): QueryKey {
  return [
    "@gleanwork/api-client",
    "usage",
    "listLimitIncreaseRequests",
    parameters,
  ];
}
