/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ce940eb10053
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { adminUsageCreateLimitIncreaseRequest } from "../funcs/adminUsageCreateLimitIncreaseRequest.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type AdminUsageCreateLimitIncreaseRequestMutationVariables = {
  request: components.PlatformAgentRequestCreate;
  options?: RequestOptions;
};

export type AdminUsageCreateLimitIncreaseRequestMutationData =
  components.PlatformRequestResponse;

export type AdminUsageCreateLimitIncreaseRequestMutationError =
  | errors.PlatformProblemDetailError
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Submit an editable-agent limit-increase request
 *
 * @remarks
 * Requires usage.limit_increase_requests:write, the same scope as personal creation, and current edit permission on the agent, not billing permissions. The caller supplies the agent, client, and optional business justification. Requester identity comes from authentication; the server assigns the request identifier and current UTC month. This internal scaffold returns 503 without creating a request.
 */
export function useAdminUsageCreateLimitIncreaseRequestMutation(
  options?: MutationHookOptions<
    AdminUsageCreateLimitIncreaseRequestMutationData,
    AdminUsageCreateLimitIncreaseRequestMutationError,
    AdminUsageCreateLimitIncreaseRequestMutationVariables
  >,
): UseMutationResult<
  AdminUsageCreateLimitIncreaseRequestMutationData,
  AdminUsageCreateLimitIncreaseRequestMutationError,
  AdminUsageCreateLimitIncreaseRequestMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildAdminUsageCreateLimitIncreaseRequestMutation(client, options),
    ...options,
  });
}

export function mutationKeyAdminUsageCreateLimitIncreaseRequest(): MutationKey {
  return ["@gleanwork/api-client", "usage", "createLimitIncreaseRequest"];
}

export function buildAdminUsageCreateLimitIncreaseRequestMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: AdminUsageCreateLimitIncreaseRequestMutationVariables,
  ) => Promise<AdminUsageCreateLimitIncreaseRequestMutationData>;
} {
  return {
    mutationKey: mutationKeyAdminUsageCreateLimitIncreaseRequest(),
    mutationFn: function adminUsageCreateLimitIncreaseRequestMutationFn({
      request,
      options,
    }): Promise<AdminUsageCreateLimitIncreaseRequestMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(adminUsageCreateLimitIncreaseRequest(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
