/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8e955bf32231
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { adminUsageUpdateSettings } from "../funcs/adminUsageUpdateSettings.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type AdminUsageUpdateSettingsMutationVariables = {
  request: components.PlatformUsageSettingsUpdateRequestUnion;
  options?: RequestOptions;
};

export type AdminUsageUpdateSettingsMutationData =
  components.PlatformUsageSettingsResponse;

export type AdminUsageUpdateSettingsMutationError =
  | errors.PlatformProblemDetailError
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Update usage settings
 *
 * @remarks
 * Partially update workspace-wide usage settings. Requires admin.usage.settings:write and permission to edit workspace billing; a global administrator role is not required.
 */
export function useAdminUsageUpdateSettingsMutation(
  options?: MutationHookOptions<
    AdminUsageUpdateSettingsMutationData,
    AdminUsageUpdateSettingsMutationError,
    AdminUsageUpdateSettingsMutationVariables
  >,
): UseMutationResult<
  AdminUsageUpdateSettingsMutationData,
  AdminUsageUpdateSettingsMutationError,
  AdminUsageUpdateSettingsMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildAdminUsageUpdateSettingsMutation(client, options),
    ...options,
  });
}

export function mutationKeyAdminUsageUpdateSettings(): MutationKey {
  return ["@gleanwork/api-client", "usage", "updateSettings"];
}

export function buildAdminUsageUpdateSettingsMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: AdminUsageUpdateSettingsMutationVariables,
  ) => Promise<AdminUsageUpdateSettingsMutationData>;
} {
  return {
    mutationKey: mutationKeyAdminUsageUpdateSettings(),
    mutationFn: function adminUsageUpdateSettingsMutationFn({
      request,
      options,
    }): Promise<AdminUsageUpdateSettingsMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(adminUsageUpdateSettings(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
