/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e9ad48bcd941
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { agentsRespondToRun } from "../funcs/agentsRespondToRun.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type AgentsRespondToRunMutationVariables = {
  platformAgentRunResponsesRequest: components.PlatformAgentRunResponsesRequest;
  agentId: string;
  options?: RequestOptions;
};

export type AgentsRespondToRunMutationData =
  components.PlatformAgentRunResponse;

export type AgentsRespondToRunMutationError =
  | errors.PlatformProblemDetailError
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Respond to agent run approvals
 *
 * @remarks
 * Submit decisions for every pending tool approval in the paused run's current batch. The run is identified by `run_id` in the JSON body. Decisions apply only to the stored invocations and arguments; argument edits, authentication responses, and session-wide grants are not supported. The caller must own the run, still have agent access, and have the agents.run scope. Acceptance persists the decisions before resuming the same run and chat session. Identical accepted decisions return the current snapshot without another continuation. Conflicting, stale, incomplete, or non-pending decisions return 409. Cancellation registration failure returns 503 without accepting the decisions; retry the same approval batch. This retry guarantee does not cover an indeterminate database commit outcome. Go workflow approval resumes currently support one tool invocation and one approval response. Unsupported multi-tool or multi-decision Go resumes fail without executing tools. The resumed action must resolve to the tool identified by the stored approval request and paused checkpoint. Missing or inconsistent identity fails without executing tools. Execution continues after HTTP disconnects, but is not automatically resumed after a QE crash. Each accepted continuation starts a fresh 30-minute execution timeout and 40-minute cleanup deadline. Identical retries do not extend that deadline. Waiting for approval does not expire a run. The next GET marks an overdue active turn FAILED without replaying execution.
 */
export function useAgentsRespondToRunMutation(
  options?: MutationHookOptions<
    AgentsRespondToRunMutationData,
    AgentsRespondToRunMutationError,
    AgentsRespondToRunMutationVariables
  >,
): UseMutationResult<
  AgentsRespondToRunMutationData,
  AgentsRespondToRunMutationError,
  AgentsRespondToRunMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildAgentsRespondToRunMutation(client, options),
    ...options,
  });
}

export function mutationKeyAgentsRespondToRun(): MutationKey {
  return ["@gleanwork/api-client", "agents", "respondToRun"];
}

export function buildAgentsRespondToRunMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: AgentsRespondToRunMutationVariables,
  ) => Promise<AgentsRespondToRunMutationData>;
} {
  return {
    mutationKey: mutationKeyAgentsRespondToRun(),
    mutationFn: function agentsRespondToRunMutationFn({
      platformAgentRunResponsesRequest,
      agentId,
      options,
    }): Promise<AgentsRespondToRunMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(agentsRespondToRun(
        client$,
        platformAgentRunResponsesRequest,
        agentId,
        mergedOptions,
      ));
    },
  };
}
