/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 50ee42338ff5
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { useGleanContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  AgentsGetRunQueryData,
  buildAgentsGetRunQuery,
  prefetchAgentsGetRun,
  queryKeyAgentsGetRun,
} from "./agentsGetRun.core.js";
export {
  type AgentsGetRunQueryData,
  buildAgentsGetRunQuery,
  prefetchAgentsGetRun,
  queryKeyAgentsGetRun,
};

export type AgentsGetRunQueryError =
  | errors.PlatformProblemDetailError
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get agent run
 *
 * @remarks
 * Retrieve a persisted workflow execution owned by the authenticated user. The run must belong to the specified agent, and the user must still have access to that agent. Unknown runs, runs owned by another user, and mismatched agent/run identifiers return 404. Requires the agents.run scope. Executions without a persisted workflow record are not available through this endpoint.
 */
export function useAgentsGetRun(
  agentId: string,
  runId: string,
  options?: QueryHookOptions<AgentsGetRunQueryData, AgentsGetRunQueryError>,
): UseQueryResult<AgentsGetRunQueryData, AgentsGetRunQueryError> {
  const client = useGleanContext();
  return useQuery({
    ...buildAgentsGetRunQuery(
      client,
      agentId,
      runId,
      options,
    ),
    ...options,
  });
}

/**
 * Get agent run
 *
 * @remarks
 * Retrieve a persisted workflow execution owned by the authenticated user. The run must belong to the specified agent, and the user must still have access to that agent. Unknown runs, runs owned by another user, and mismatched agent/run identifiers return 404. Requires the agents.run scope. Executions without a persisted workflow record are not available through this endpoint.
 */
export function useAgentsGetRunSuspense(
  agentId: string,
  runId: string,
  options?: SuspenseQueryHookOptions<
    AgentsGetRunQueryData,
    AgentsGetRunQueryError
  >,
): UseSuspenseQueryResult<AgentsGetRunQueryData, AgentsGetRunQueryError> {
  const client = useGleanContext();
  return useSuspenseQuery({
    ...buildAgentsGetRunQuery(
      client,
      agentId,
      runId,
      options,
    ),
    ...options,
  });
}

export function setAgentsGetRunData(
  client: QueryClient,
  queryKeyBase: [agentId: string, runId: string],
  data: AgentsGetRunQueryData,
): AgentsGetRunQueryData | undefined {
  const key = queryKeyAgentsGetRun(...queryKeyBase);

  return client.setQueryData<AgentsGetRunQueryData>(key, data);
}

export function invalidateAgentsGetRun(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[agentId: string, runId: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gleanwork/api-client", "agents", "getRun", ...queryKeyBase],
  });
}

export function invalidateAllAgentsGetRun(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gleanwork/api-client", "agents", "getRun"],
  });
}
