/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b1268b5938b6
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import {
  agentsCreateRun,
  CreateRunAcceptEnum,
} from "../funcs/agentsCreateRun.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export { CreateRunAcceptEnum } from "../funcs/agentsCreateRun.js";

export type AgentsCreateRunMutationVariables = {
  platformAgentRunCreateRequest: components.PlatformAgentRunCreateRequest;
  agentId: string;
  options?: RequestOptions & { acceptHeaderOverride?: CreateRunAcceptEnum };
};

export type AgentsCreateRunMutationData =
  operations.PlatformAgentsCreateRunResponse;

export type AgentsCreateRunMutationError =
  | errors.PlatformUnauthorizedAgentToolsProblemError
  | errors.PlatformProblemDetailError
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Create agent run
 *
 * @remarks
 * Execute an agent run. By default, set `stream` to true to receive server-sent events; otherwise the response contains the final agent messages. Set `execution_mode` to `DURABLE` to persist a new run and return its initial snapshot with HTTP 201 without waiting for execution. Poll the agent-scoped GET run endpoint for progress. Durable execution continues after an HTTP disconnect, but is not automatically resumed after a QE restart or crash. An active turn becomes overdue more than 40 minutes after acceptance (a 30-minute execution timeout plus 10 minutes of grace). The next GET of the run marks the overdue turn FAILED without replay; there is no periodic sweep. Without a GET, the stored run can remain RUNNING. Failure does not prove that external tool work has stopped. Paused runs are not expired. Each POST creates a new run; retrying a POST can create another execution. A run tracks one workflow execution; automatic background-subagent wake turns are separate executions, not continuations tracked by this run ID.
 */
export function useAgentsCreateRunMutation(
  options?: MutationHookOptions<
    AgentsCreateRunMutationData,
    AgentsCreateRunMutationError,
    AgentsCreateRunMutationVariables
  >,
): UseMutationResult<
  AgentsCreateRunMutationData,
  AgentsCreateRunMutationError,
  AgentsCreateRunMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildAgentsCreateRunMutation(client, options),
    ...options,
  });
}

export function mutationKeyAgentsCreateRun(): MutationKey {
  return ["@gleanwork/api-client", "agents", "createRun"];
}

export function buildAgentsCreateRunMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions & { acceptHeaderOverride?: CreateRunAcceptEnum },
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: AgentsCreateRunMutationVariables,
  ) => Promise<AgentsCreateRunMutationData>;
} {
  return {
    mutationKey: mutationKeyAgentsCreateRun(),
    mutationFn: function agentsCreateRunMutationFn({
      platformAgentRunCreateRequest,
      agentId,
      options,
    }): Promise<AgentsCreateRunMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(agentsCreateRun(
        client$,
        platformAgentRunCreateRequest,
        agentId,
        mergedOptions,
      ));
    },
  };
}
