/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 26e1ed795930
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { agentsCancelRun } from "../funcs/agentsCancelRun.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type AgentsCancelRunMutationVariables = {
  platformAgentRunCancellationRequest:
    components.PlatformAgentRunCancellationRequest;
  agentId: string;
  options?: RequestOptions;
};

export type AgentsCancelRunMutationData = components.PlatformAgentRunResponse;

export type AgentsCancelRunMutationError =
  | errors.PlatformProblemDetailError
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Cancel an agent run
 *
 * @remarks
 * Request cooperative cancellation of the durable agent run identified by `run_id` in the JSON body. Requires ownership, current agent access, and the agents.run scope. Sending a cancellation signal does not itself change an active run from RUNNING; poll GET run for the final state. Paused runs become CANCELLED without resuming execution. Repeated requests and requests for terminal runs return the current snapshot. Completion may win a race with cancellation. Completed tool side effects cannot be undone, and external work may continue if a tool does not support cancellation. Cancellation targets this run, not separate background-subagent executions. An active run without a cancellation registration returns 409. Cancellation signaling requires Redis. An interrupted active run can instead become FAILED through deadline cleanup; this does not verify that external tool work has stopped.
 */
export function useAgentsCancelRunMutation(
  options?: MutationHookOptions<
    AgentsCancelRunMutationData,
    AgentsCancelRunMutationError,
    AgentsCancelRunMutationVariables
  >,
): UseMutationResult<
  AgentsCancelRunMutationData,
  AgentsCancelRunMutationError,
  AgentsCancelRunMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildAgentsCancelRunMutation(client, options),
    ...options,
  });
}

export function mutationKeyAgentsCancelRun(): MutationKey {
  return ["@gleanwork/api-client", "agents", "cancelRun"];
}

export function buildAgentsCancelRunMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: AgentsCancelRunMutationVariables,
  ) => Promise<AgentsCancelRunMutationData>;
} {
  return {
    mutationKey: mutationKeyAgentsCancelRun(),
    mutationFn: function agentsCancelRunMutationFn({
      platformAgentRunCancellationRequest,
      agentId,
      options,
    }): Promise<AgentsCancelRunMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(agentsCancelRun(
        client$,
        platformAgentRunCancellationRequest,
        agentId,
        mergedOptions,
      ));
    },
  };
}
