/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useGleanContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildClientAgentsRetrieveSchemasQuery,
  ClientAgentsRetrieveSchemasQueryData,
  prefetchClientAgentsRetrieveSchemas,
  queryKeyClientAgentsRetrieveSchemas,
} from "./clientAgentsRetrieveSchemas.core.js";
export {
  buildClientAgentsRetrieveSchemasQuery,
  type ClientAgentsRetrieveSchemasQueryData,
  prefetchClientAgentsRetrieveSchemas,
  queryKeyClientAgentsRetrieveSchemas,
};

/**
 * List an agent's schemas
 *
 * @remarks
 * Return [agent](https://developers.glean.com/agents/agents-api)'s input and output schemas. You can use these schemas to detect changes to an agent's input or output structure.
 */
export function useClientAgentsRetrieveSchemas(
  agentId: string,
  timezoneOffset?: number | undefined,
  options?: QueryHookOptions<ClientAgentsRetrieveSchemasQueryData>,
): UseQueryResult<ClientAgentsRetrieveSchemasQueryData, Error> {
  const client = useGleanContext();
  return useQuery({
    ...buildClientAgentsRetrieveSchemasQuery(
      client,
      agentId,
      timezoneOffset,
      options,
    ),
    ...options,
  });
}

/**
 * List an agent's schemas
 *
 * @remarks
 * Return [agent](https://developers.glean.com/agents/agents-api)'s input and output schemas. You can use these schemas to detect changes to an agent's input or output structure.
 */
export function useClientAgentsRetrieveSchemasSuspense(
  agentId: string,
  timezoneOffset?: number | undefined,
  options?: SuspenseQueryHookOptions<ClientAgentsRetrieveSchemasQueryData>,
): UseSuspenseQueryResult<ClientAgentsRetrieveSchemasQueryData, Error> {
  const client = useGleanContext();
  return useSuspenseQuery({
    ...buildClientAgentsRetrieveSchemasQuery(
      client,
      agentId,
      timezoneOffset,
      options,
    ),
    ...options,
  });
}

export function setClientAgentsRetrieveSchemasData(
  client: QueryClient,
  queryKeyBase: [
    agentId: string,
    parameters: { timezoneOffset?: number | undefined },
  ],
  data: ClientAgentsRetrieveSchemasQueryData,
): ClientAgentsRetrieveSchemasQueryData | undefined {
  const key = queryKeyClientAgentsRetrieveSchemas(...queryKeyBase);

  return client.setQueryData<ClientAgentsRetrieveSchemasQueryData>(key, data);
}

export function invalidateClientAgentsRetrieveSchemas(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [agentId: string, parameters: { timezoneOffset?: number | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@gleanwork/api-client",
      "agents",
      "retrieveSchemas",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllClientAgentsRetrieveSchemas(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gleanwork/api-client", "agents", "retrieveSchemas"],
  });
}
