/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 501f802dd053
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientActivityFeedback } from "../funcs/clientActivityFeedback.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientActivityFeedbackMutationVariables = {
  feedback1?: components.Feedback | undefined;
  feedbackQueryParameter?: string | undefined;
  options?: RequestOptions;
};

export type ClientActivityFeedbackMutationData = void;

export type ClientActivityFeedbackMutationError =
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Report client activity
 *
 * @remarks
 * Report events that happen to results within a Glean client UI, such as search result views and clicks.  This signal improves search quality.
 */
export function useClientActivityFeedbackMutation(
  options?: MutationHookOptions<
    ClientActivityFeedbackMutationData,
    ClientActivityFeedbackMutationError,
    ClientActivityFeedbackMutationVariables
  >,
): UseMutationResult<
  ClientActivityFeedbackMutationData,
  ClientActivityFeedbackMutationError,
  ClientActivityFeedbackMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientActivityFeedbackMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientActivityFeedback(): MutationKey {
  return ["@gleanwork/api-client", "activity", "feedback"];
}

export function buildClientActivityFeedbackMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientActivityFeedbackMutationVariables,
  ) => Promise<ClientActivityFeedbackMutationData>;
} {
  return {
    mutationKey: mutationKeyClientActivityFeedback(),
    mutationFn: function clientActivityFeedbackMutationFn({
      feedback1,
      feedbackQueryParameter,
      options,
    }): Promise<ClientActivityFeedbackMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientActivityFeedback(
        client$,
        feedback1,
        feedbackQueryParameter,
        mergedOptions,
      ));
    },
  };
}
