/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientGovernanceDataPoliciesDownload } from "../funcs/clientGovernanceDataPoliciesDownload.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
export type ClientGovernanceDataPoliciesDownloadQueryData = string;

export function prefetchClientGovernanceDataPoliciesDownload(
  queryClient: QueryClient,
  client$: GleanCore,
  id: string,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildClientGovernanceDataPoliciesDownloadQuery(
      client$,
      id,
      options,
    ),
  });
}

export function buildClientGovernanceDataPoliciesDownloadQuery(
  client$: GleanCore,
  id: string,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ClientGovernanceDataPoliciesDownloadQueryData>;
} {
  return {
    queryKey: queryKeyClientGovernanceDataPoliciesDownload(id),
    queryFn: async function clientGovernanceDataPoliciesDownloadQueryFn(
      ctx,
    ): Promise<ClientGovernanceDataPoliciesDownloadQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(clientGovernanceDataPoliciesDownload(
        client$,
        id,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyClientGovernanceDataPoliciesDownload(
  id: string,
): QueryKey {
  return ["@gleanwork/api-client", "policies", "download", id];
}
