/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 762fff176fd6
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientPinsList } from "../funcs/clientPinsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientPinsListMutationVariables = {
  requestBody: operations.ListpinsRequestBody;
  locale?: string | undefined;
  options?: RequestOptions;
};

export type ClientPinsListMutationData = components.ListPinsResponse;

export type ClientPinsListMutationError =
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * List pins
 *
 * @remarks
 * Lists all pins.
 */
export function useClientPinsListMutation(
  options?: MutationHookOptions<
    ClientPinsListMutationData,
    ClientPinsListMutationError,
    ClientPinsListMutationVariables
  >,
): UseMutationResult<
  ClientPinsListMutationData,
  ClientPinsListMutationError,
  ClientPinsListMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientPinsListMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientPinsList(): MutationKey {
  return ["@gleanwork/api-client", "pins", "list"];
}

export function buildClientPinsListMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientPinsListMutationVariables,
  ) => Promise<ClientPinsListMutationData>;
} {
  return {
    mutationKey: mutationKeyClientPinsList(),
    mutationFn: function clientPinsListMutationFn({
      requestBody,
      locale,
      options,
    }): Promise<ClientPinsListMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientPinsList(
        client$,
        requestBody,
        locale,
        mergedOptions,
      ));
    },
  };
}
