/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 46cdea1cdff3
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientPinsRetrieve } from "../funcs/clientPinsRetrieve.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientPinsRetrieveMutationVariables = {
  getPinRequest: components.GetPinRequest;
  locale?: string | undefined;
  options?: RequestOptions;
};

export type ClientPinsRetrieveMutationData = components.GetPinResponse;

export type ClientPinsRetrieveMutationError =
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Read pin
 *
 * @remarks
 * Read pin details given its ID.
 */
export function useClientPinsRetrieveMutation(
  options?: MutationHookOptions<
    ClientPinsRetrieveMutationData,
    ClientPinsRetrieveMutationError,
    ClientPinsRetrieveMutationVariables
  >,
): UseMutationResult<
  ClientPinsRetrieveMutationData,
  ClientPinsRetrieveMutationError,
  ClientPinsRetrieveMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientPinsRetrieveMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientPinsRetrieve(): MutationKey {
  return ["@gleanwork/api-client", "pins", "retrieve"];
}

export function buildClientPinsRetrieveMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientPinsRetrieveMutationVariables,
  ) => Promise<ClientPinsRetrieveMutationData>;
} {
  return {
    mutationKey: mutationKeyClientPinsRetrieve(),
    mutationFn: function clientPinsRetrieveMutationFn({
      getPinRequest,
      locale,
      options,
    }): Promise<ClientPinsRetrieveMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientPinsRetrieve(
        client$,
        getPinRequest,
        locale,
        mergedOptions,
      ));
    },
  };
}
