/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1cdcec30fb93
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientSearchQuery } from "../funcs/clientSearchQuery.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientSearchQueryMutationVariables = {
  searchRequest: components.SearchRequest;
  locale?: string | undefined;
  options?: RequestOptions;
};

export type ClientSearchQueryMutationData = components.SearchResponse;

export type ClientSearchQueryMutationError =
  | errors.GleanDataError
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Search
 *
 * @remarks
 * Retrieve results from the index for the given query and filters.
 */
export function useClientSearchQueryMutation(
  options?: MutationHookOptions<
    ClientSearchQueryMutationData,
    ClientSearchQueryMutationError,
    ClientSearchQueryMutationVariables
  >,
): UseMutationResult<
  ClientSearchQueryMutationData,
  ClientSearchQueryMutationError,
  ClientSearchQueryMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientSearchQueryMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientSearchQuery(): MutationKey {
  return ["@gleanwork/api-client", "search", "query"];
}

export function buildClientSearchQueryMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientSearchQueryMutationVariables,
  ) => Promise<ClientSearchQueryMutationData>;
} {
  return {
    mutationKey: mutationKeyClientSearchQuery(),
    mutationFn: function clientSearchQueryMutationFn({
      searchRequest,
      locale,
      options,
    }): Promise<ClientSearchQueryMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientSearchQuery(
        client$,
        searchRequest,
        locale,
        mergedOptions,
      ));
    },
  };
}
