/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { clientAnnouncementsCreate } from "../funcs/clientAnnouncementsCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ClientAnnouncementsCreateMutationVariables = {
  createAnnouncementRequest: components.CreateAnnouncementRequest;
  locale?: string | undefined;
  options?: RequestOptions;
};

export type ClientAnnouncementsCreateMutationData = components.Announcement;

export type ClientAnnouncementsCreateMutationError =
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Create Announcement
 *
 * @remarks
 * Create a textual announcement visible to some set of users based on department and location.
 */
export function useClientAnnouncementsCreateMutation(
  options?: MutationHookOptions<
    ClientAnnouncementsCreateMutationData,
    ClientAnnouncementsCreateMutationError,
    ClientAnnouncementsCreateMutationVariables
  >,
): UseMutationResult<
  ClientAnnouncementsCreateMutationData,
  ClientAnnouncementsCreateMutationError,
  ClientAnnouncementsCreateMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildClientAnnouncementsCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyClientAnnouncementsCreate(): MutationKey {
  return ["@gleanwork/api-client", "announcements", "create"];
}

export function buildClientAnnouncementsCreateMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ClientAnnouncementsCreateMutationVariables,
  ) => Promise<ClientAnnouncementsCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyClientAnnouncementsCreate(),
    mutationFn: function clientAnnouncementsCreateMutationFn({
      createAnnouncementRequest,
      locale,
      options,
    }): Promise<ClientAnnouncementsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(clientAnnouncementsCreate(
        client$,
        createAnnouncementRequest,
        locale,
        mergedOptions,
      ));
    },
  };
}
