/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useGleanContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildClientToolsListQuery,
  ClientToolsListQueryData,
  prefetchClientToolsList,
  queryKeyClientToolsList,
} from "./clientToolsList.core.js";
export {
  buildClientToolsListQuery,
  type ClientToolsListQueryData,
  prefetchClientToolsList,
  queryKeyClientToolsList,
};

/**
 * List available tools
 *
 * @remarks
 * Returns a filtered set of available tools based on optional tool name parameters. If no filters are provided, all available tools are returned.
 */
export function useClientToolsList(
  toolNames?: Array<string> | undefined,
  options?: QueryHookOptions<ClientToolsListQueryData>,
): UseQueryResult<ClientToolsListQueryData, Error> {
  const client = useGleanContext();
  return useQuery({
    ...buildClientToolsListQuery(
      client,
      toolNames,
      options,
    ),
    ...options,
  });
}

/**
 * List available tools
 *
 * @remarks
 * Returns a filtered set of available tools based on optional tool name parameters. If no filters are provided, all available tools are returned.
 */
export function useClientToolsListSuspense(
  toolNames?: Array<string> | undefined,
  options?: SuspenseQueryHookOptions<ClientToolsListQueryData>,
): UseSuspenseQueryResult<ClientToolsListQueryData, Error> {
  const client = useGleanContext();
  return useSuspenseQuery({
    ...buildClientToolsListQuery(
      client,
      toolNames,
      options,
    ),
    ...options,
  });
}

export function setClientToolsListData(
  client: QueryClient,
  queryKeyBase: [parameters: { toolNames?: Array<string> | undefined }],
  data: ClientToolsListQueryData,
): ClientToolsListQueryData | undefined {
  const key = queryKeyClientToolsList(...queryKeyBase);

  return client.setQueryData<ClientToolsListQueryData>(key, data);
}

export function invalidateClientToolsList(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: { toolNames?: Array<string> | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gleanwork/api-client", "tools", "list", ...queryKeyBase],
  });
}

export function invalidateAllClientToolsList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gleanwork/api-client", "tools", "list"],
  });
}
