/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8429e29d8f7c
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { useGleanContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildDepartmentsListQuery,
  DepartmentsListQueryData,
  prefetchDepartmentsList,
  queryKeyDepartmentsList,
} from "./departmentsList.core.js";
export {
  buildDepartmentsListQuery,
  type DepartmentsListQueryData,
  prefetchDepartmentsList,
  queryKeyDepartmentsList,
};

export type DepartmentsListQueryError =
  | errors.PlatformProblemDetailError
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * List departments
 *
 * @remarks
 * List the departments in the Glean directory, ordered by display_name and then by department_id. A department is active when at least one active user belongs to it. A department is inactive when only inactive users, such as former employees, belong to it, or when only a usage limit names it. Inactive departments are left out unless an is_active filter includes the value "false". Department names are exact, so names that differ only by case are different departments.
 */
export function useDepartmentsList(
  pageSize?: number | undefined,
  cursor?: string | undefined,
  filters?: Array<components.PlatformDepartmentFilter> | undefined,
  options?: QueryHookOptions<
    DepartmentsListQueryData,
    DepartmentsListQueryError
  >,
): UseQueryResult<DepartmentsListQueryData, DepartmentsListQueryError> {
  const client = useGleanContext();
  return useQuery({
    ...buildDepartmentsListQuery(
      client,
      pageSize,
      cursor,
      filters,
      options,
    ),
    ...options,
  });
}

/**
 * List departments
 *
 * @remarks
 * List the departments in the Glean directory, ordered by display_name and then by department_id. A department is active when at least one active user belongs to it. A department is inactive when only inactive users, such as former employees, belong to it, or when only a usage limit names it. Inactive departments are left out unless an is_active filter includes the value "false". Department names are exact, so names that differ only by case are different departments.
 */
export function useDepartmentsListSuspense(
  pageSize?: number | undefined,
  cursor?: string | undefined,
  filters?: Array<components.PlatformDepartmentFilter> | undefined,
  options?: SuspenseQueryHookOptions<
    DepartmentsListQueryData,
    DepartmentsListQueryError
  >,
): UseSuspenseQueryResult<DepartmentsListQueryData, DepartmentsListQueryError> {
  const client = useGleanContext();
  return useSuspenseQuery({
    ...buildDepartmentsListQuery(
      client,
      pageSize,
      cursor,
      filters,
      options,
    ),
    ...options,
  });
}

export function setDepartmentsListData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      pageSize?: number | undefined;
      cursor?: string | undefined;
      filters?: Array<components.PlatformDepartmentFilter> | undefined;
    },
  ],
  data: DepartmentsListQueryData,
): DepartmentsListQueryData | undefined {
  const key = queryKeyDepartmentsList(...queryKeyBase);

  return client.setQueryData<DepartmentsListQueryData>(key, data);
}

export function invalidateDepartmentsList(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      pageSize?: number | undefined;
      cursor?: string | undefined;
      filters?: Array<components.PlatformDepartmentFilter> | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gleanwork/api-client", "departments", "list", ...queryKeyBase],
  });
}

export function invalidateAllDepartmentsList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gleanwork/api-client", "departments", "list"],
  });
}
