/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useGleanContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildGovernanceDownloadfindingsexportQuery,
  GovernanceDownloadfindingsexportQueryData,
  prefetchGovernanceDownloadfindingsexport,
  queryKeyGovernanceDownloadfindingsexport,
} from "./governanceDownloadfindingsexport.core.js";
export {
  buildGovernanceDownloadfindingsexportQuery,
  type GovernanceDownloadfindingsexportQueryData,
  prefetchGovernanceDownloadfindingsexport,
  queryKeyGovernanceDownloadfindingsexport,
};

/**
 * Downloads findings export
 *
 * @remarks
 * Downloads a DLP findings export as a CSV file.
 */
export function useGovernanceDownloadfindingsexport(
  id: string,
  options?: QueryHookOptions<GovernanceDownloadfindingsexportQueryData>,
): UseQueryResult<GovernanceDownloadfindingsexportQueryData, Error> {
  const client = useGleanContext();
  return useQuery({
    ...buildGovernanceDownloadfindingsexportQuery(
      client,
      id,
      options,
    ),
    ...options,
  });
}

/**
 * Downloads findings export
 *
 * @remarks
 * Downloads a DLP findings export as a CSV file.
 */
export function useGovernanceDownloadfindingsexportSuspense(
  id: string,
  options?: SuspenseQueryHookOptions<GovernanceDownloadfindingsexportQueryData>,
): UseSuspenseQueryResult<GovernanceDownloadfindingsexportQueryData, Error> {
  const client = useGleanContext();
  return useSuspenseQuery({
    ...buildGovernanceDownloadfindingsexportQuery(
      client,
      id,
      options,
    ),
    ...options,
  });
}

export function setGovernanceDownloadfindingsexportData(
  client: QueryClient,
  queryKeyBase: [id: string],
  data: GovernanceDownloadfindingsexportQueryData,
): GovernanceDownloadfindingsexportQueryData | undefined {
  const key = queryKeyGovernanceDownloadfindingsexport(...queryKeyBase);

  return client.setQueryData<GovernanceDownloadfindingsexportQueryData>(
    key,
    data,
  );
}

export function invalidateGovernanceDownloadfindingsexport(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<[id: string]>,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@gleanwork/api-client",
      "Governance",
      "downloadfindingsexport",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllGovernanceDownloadfindingsexport(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gleanwork/api-client", "Governance", "downloadfindingsexport"],
  });
}
