/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f4da9df8520b
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { indexingDocumentsIndex } from "../funcs/indexingDocumentsIndex.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type IndexingDocumentsIndexMutationVariables = {
  request: components.IndexDocumentsRequest;
  options?: RequestOptions;
};

export type IndexingDocumentsIndexMutationData = void;

export type IndexingDocumentsIndexMutationError =
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Index documents
 *
 * @remarks
 * Adds or updates multiple documents in the index. Please refer to the [bulk indexing](https://developers.glean.com/indexing/documents/bulk-indexing/choosing-indexdocuments-vs-bulkindexdocuments) documentation for an explanation of when to use this endpoint.
 */
export function useIndexingDocumentsIndexMutation(
  options?: MutationHookOptions<
    IndexingDocumentsIndexMutationData,
    IndexingDocumentsIndexMutationError,
    IndexingDocumentsIndexMutationVariables
  >,
): UseMutationResult<
  IndexingDocumentsIndexMutationData,
  IndexingDocumentsIndexMutationError,
  IndexingDocumentsIndexMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildIndexingDocumentsIndexMutation(client, options),
    ...options,
  });
}

export function mutationKeyIndexingDocumentsIndex(): MutationKey {
  return ["@gleanwork/api-client", "documents", "index"];
}

export function buildIndexingDocumentsIndexMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: IndexingDocumentsIndexMutationVariables,
  ) => Promise<IndexingDocumentsIndexMutationData>;
} {
  return {
    mutationKey: mutationKeyIndexingDocumentsIndex(),
    mutationFn: function indexingDocumentsIndexMutationFn({
      request,
      options,
    }): Promise<IndexingDocumentsIndexMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(indexingDocumentsIndex(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
