/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 52db8ffadd2a
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { platformSearchQuery } from "../funcs/platformSearchQuery.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type PlatformSearchQueryMutationVariables = {
  request: components.PlatformSearchRequest;
  options?: RequestOptions;
};

export type PlatformSearchQueryMutationData = components.PlatformSearchResponse;

export type PlatformSearchQueryMutationError =
  | errors.PlatformProblemDetailError
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Search
 *
 * @remarks
 * Execute a search query and retrieve ranked results. This is the data retrieval variant of the search API and returns only results and pagination state.
 */
export function usePlatformSearchQueryMutation(
  options?: MutationHookOptions<
    PlatformSearchQueryMutationData,
    PlatformSearchQueryMutationError,
    PlatformSearchQueryMutationVariables
  >,
): UseMutationResult<
  PlatformSearchQueryMutationData,
  PlatformSearchQueryMutationError,
  PlatformSearchQueryMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildPlatformSearchQueryMutation(client, options),
    ...options,
  });
}

export function mutationKeyPlatformSearchQuery(): MutationKey {
  return ["@gleanwork/api-client", "search", "query"];
}

export function buildPlatformSearchQueryMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: PlatformSearchQueryMutationVariables,
  ) => Promise<PlatformSearchQueryMutationData>;
} {
  return {
    mutationKey: mutationKeyPlatformSearchQuery(),
    mutationFn: function platformSearchQueryMutationFn({
      request,
      options,
    }): Promise<PlatformSearchQueryMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(platformSearchQuery(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
