/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f4f17e40da30
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { platformAgentsSearch } from "../funcs/platformAgentsSearch.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type PlatformAgentsSearchMutationVariables = {
  request: components.PlatformAgentsSearchRequest;
  options?: RequestOptions;
};

export type PlatformAgentsSearchMutationData =
  components.PlatformAgentsSearchResponse;

export type PlatformAgentsSearchMutationError =
  | errors.PlatformProblemDetailError
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Search agents
 *
 * @remarks
 * Search agents available to the authenticated user by agent name.
 */
export function usePlatformAgentsSearchMutation(
  options?: MutationHookOptions<
    PlatformAgentsSearchMutationData,
    PlatformAgentsSearchMutationError,
    PlatformAgentsSearchMutationVariables
  >,
): UseMutationResult<
  PlatformAgentsSearchMutationData,
  PlatformAgentsSearchMutationError,
  PlatformAgentsSearchMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildPlatformAgentsSearchMutation(client, options),
    ...options,
  });
}

export function mutationKeyPlatformAgentsSearch(): MutationKey {
  return ["@gleanwork/api-client", "agents", "search"];
}

export function buildPlatformAgentsSearchMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: PlatformAgentsSearchMutationVariables,
  ) => Promise<PlatformAgentsSearchMutationData>;
} {
  return {
    mutationKey: mutationKeyPlatformAgentsSearch(),
    mutationFn: function platformAgentsSearchMutationFn({
      request,
      options,
    }): Promise<PlatformAgentsSearchMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(platformAgentsSearch(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
