/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f270a8f770bf
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { useGleanContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildSkillsListVersionsQuery,
  prefetchSkillsListVersions,
  queryKeySkillsListVersions,
  SkillsListVersionsQueryData,
} from "./skillsListVersions.core.js";
export {
  buildSkillsListVersionsQuery,
  prefetchSkillsListVersions,
  queryKeySkillsListVersions,
  type SkillsListVersionsQueryData,
};

export type SkillsListVersionsQueryError =
  | errors.PlatformProblemDetailError
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * List skill versions
 *
 * @remarks
 * List versions for a skill available to the authenticated user.
 */
export function useSkillsListVersions(
  skillId: string,
  pageSize?: number | undefined,
  cursor?: string | undefined,
  options?: QueryHookOptions<
    SkillsListVersionsQueryData,
    SkillsListVersionsQueryError
  >,
): UseQueryResult<SkillsListVersionsQueryData, SkillsListVersionsQueryError> {
  const client = useGleanContext();
  return useQuery({
    ...buildSkillsListVersionsQuery(
      client,
      skillId,
      pageSize,
      cursor,
      options,
    ),
    ...options,
  });
}

/**
 * List skill versions
 *
 * @remarks
 * List versions for a skill available to the authenticated user.
 */
export function useSkillsListVersionsSuspense(
  skillId: string,
  pageSize?: number | undefined,
  cursor?: string | undefined,
  options?: SuspenseQueryHookOptions<
    SkillsListVersionsQueryData,
    SkillsListVersionsQueryError
  >,
): UseSuspenseQueryResult<
  SkillsListVersionsQueryData,
  SkillsListVersionsQueryError
> {
  const client = useGleanContext();
  return useSuspenseQuery({
    ...buildSkillsListVersionsQuery(
      client,
      skillId,
      pageSize,
      cursor,
      options,
    ),
    ...options,
  });
}

export function setSkillsListVersionsData(
  client: QueryClient,
  queryKeyBase: [
    skillId: string,
    parameters: { pageSize?: number | undefined; cursor?: string | undefined },
  ],
  data: SkillsListVersionsQueryData,
): SkillsListVersionsQueryData | undefined {
  const key = queryKeySkillsListVersions(...queryKeyBase);

  return client.setQueryData<SkillsListVersionsQueryData>(key, data);
}

export function invalidateSkillsListVersions(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      skillId: string,
      parameters: {
        pageSize?: number | undefined;
        cursor?: string | undefined;
      },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@gleanwork/api-client",
      "skills",
      "listVersions",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllSkillsListVersions(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@gleanwork/api-client", "skills", "listVersions"],
  });
}
