/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 740cd8836341
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { skillsRetrieveVersionContent } from "../funcs/skillsRetrieveVersionContent.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type SkillsRetrieveVersionContentQueryData =
  operations.PlatformSkillsGetVersionContentResponse;

export function prefetchSkillsRetrieveVersionContent(
  queryClient: QueryClient,
  client$: GleanCore,
  skillId: string,
  version: number,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildSkillsRetrieveVersionContentQuery(
      client$,
      skillId,
      version,
      options,
    ),
  });
}

export function buildSkillsRetrieveVersionContentQuery(
  client$: GleanCore,
  skillId: string,
  version: number,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<SkillsRetrieveVersionContentQueryData>;
} {
  return {
    queryKey: queryKeySkillsRetrieveVersionContent(skillId, version),
    queryFn: async function skillsRetrieveVersionContentQueryFn(
      ctx,
    ): Promise<SkillsRetrieveVersionContentQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(skillsRetrieveVersionContent(
        client$,
        skillId,
        version,
        mergedOptions,
      ));
    },
  };
}

export function queryKeySkillsRetrieveVersionContent(
  skillId: string,
  version: number,
): QueryKey {
  return [
    "@gleanwork/api-client",
    "skills",
    "retrieveVersionContent",
    skillId,
    version,
  ];
}
