/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 25aad4d97aeb
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { GleanCore } from "../core.js";
import { troubleshootingPostApiIndexV1DebugDatasourceDocumentEvents } from "../funcs/troubleshootingPostApiIndexV1DebugDatasourceDocumentEvents.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { GleanBaseError } from "../models/errors/gleanbaseerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useGleanContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationVariables =
  {
    debugDocumentLifecycleRequest: components.DebugDocumentLifecycleRequest;
    datasource: string;
    options?: RequestOptions;
  };

export type TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationData =
  components.DebugDocumentLifecycleResponse;

export type TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationError =
  | GleanBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Beta: Get document lifecycle events
 *
 * @remarks
 * Retrieves lifecycle events for a specific document including upload time, index times and deletions. Rate limited to 1 request per minute per datasource. Currently in beta, might undergo breaking changes without prior notice.
 */
export function useTroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutation(
  options?: MutationHookOptions<
    TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationData,
    TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationError,
    TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationVariables
  >,
): UseMutationResult<
  TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationData,
  TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationError,
  TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationVariables
> {
  const client = useGleanContext();
  return useMutation({
    ...buildTroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutation(
      client,
      options,
    ),
    ...options,
  });
}

export function mutationKeyTroubleshootingPostApiIndexV1DebugDatasourceDocumentEvents(): MutationKey {
  return [
    "@gleanwork/api-client",
    "Troubleshooting",
    "postApiIndexV1DebugDatasourceDocumentEvents",
  ];
}

export function buildTroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutation(
  client$: GleanCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables:
      TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationVariables,
  ) => Promise<
    TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationData
  >;
} {
  return {
    mutationKey:
      mutationKeyTroubleshootingPostApiIndexV1DebugDatasourceDocumentEvents(),
    mutationFn:
      function troubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationFn(
        {
          debugDocumentLifecycleRequest,
          datasource,
          options,
        },
      ): Promise<
        TroubleshootingPostApiIndexV1DebugDatasourceDocumentEventsMutationData
      > {
        const mergedOptions = {
          ...hookOptions,
          ...options,
          fetchOptions: {
            ...hookOptions?.fetchOptions,
            ...options?.fetchOptions,
            signal: combineSignals(
              hookOptions?.fetchOptions?.signal,
              options?.fetchOptions?.signal,
            ),
          },
        };
        return unwrapAsync(
          troubleshootingPostApiIndexV1DebugDatasourceDocumentEvents(
            client$,
            debugDocumentLifecycleRequest,
            datasource,
            mergedOptions,
          ),
        );
      },
  };
}
