/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 14e1d9c7c1f2
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PlatformTriggersCreateTriggerWebhookEventRequest = {
  /**
   * Opaque delivery ID. It remains stable across retries of the same event and can be used as an idempotency key.
   */
  "webhook-id": string;
  /**
   * Unix time in seconds when this delivery attempt was signed.
   */
  "webhook-timestamp": number;
  /**
   * `v1,` followed by the standard Base64-encoded HMAC-SHA256 digest. To verify it, remove the
   *
   * @remarks
   * `whsec_` prefix from `signing_secret`, standard-Base64-decode the remainder, and use those
   * bytes as the HMAC key. Sign the UTF-8 bytes of `webhook-id + "." + webhook-timestamp + "."
   * + raw request body`. Verify the signature against the unmodified request body before
   * parsing JSON, and use a constant-time comparison.
   *
   * Fixed test vector (the raw body is one line with no trailing newline):
   *
   * - decoded signing key bytes (UTF-8; test only): `test_webhook_signing_secret_1234`
   * - `webhook-id`: `81e6dc877ac553ef96ecbc939c1e46431159491991ba55cd131fbd0e3746c6bc`
   * - `webhook-timestamp`: `1700000000`
   * - `raw request body`: `{"version":"1","trigger_id":"trigger_test_123","datasource":"GITHUB","reason":"REVIEW_REQUESTED","doc_type":"pull","event_type":"DOCUMENT_CHANGE","doc_id":"GITHUB_pull_123","view_url":"https://github.com/acme/payments-api/pull/123","title":"Add retry backoff to the crawler","event_time":"2025-04-23T11:00:00Z"}`
   * - `webhook-signature`: `v1,JqvHW0dwAOSLndiwQdXLUS/P+2RvOO8x4sOWgA/w0Gs=`
   */
  "webhook-signature": string;
  platformTriggerWebhookEvent: components.PlatformTriggerWebhookEvent;
};

/** @internal */
export const PlatformTriggersCreateTriggerWebhookEventRequest$inboundSchema:
  z.ZodType<
    PlatformTriggersCreateTriggerWebhookEventRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    "webhook-id": z.string(),
    "webhook-timestamp": z.number().int(),
    "webhook-signature": z.string(),
    PlatformTriggerWebhookEvent:
      components.PlatformTriggerWebhookEvent$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "webhook-id": "webhook-id",
      "webhook-timestamp": "webhook-timestamp",
      "webhook-signature": "webhook-signature",
      "PlatformTriggerWebhookEvent": "platformTriggerWebhookEvent",
    });
  });
/** @internal */
export type PlatformTriggersCreateTriggerWebhookEventRequest$Outbound = {
  "webhook-id": string;
  "webhook-timestamp": number;
  "webhook-signature": string;
  PlatformTriggerWebhookEvent: components.PlatformTriggerWebhookEvent$Outbound;
};

/** @internal */
export const PlatformTriggersCreateTriggerWebhookEventRequest$outboundSchema:
  z.ZodType<
    PlatformTriggersCreateTriggerWebhookEventRequest$Outbound,
    z.ZodTypeDef,
    PlatformTriggersCreateTriggerWebhookEventRequest
  > = z.object({
    "webhook-id": z.string(),
    "webhook-timestamp": z.number().int(),
    "webhook-signature": z.string(),
    platformTriggerWebhookEvent:
      components.PlatformTriggerWebhookEvent$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "webhook-id": "webhook-id",
      "webhook-timestamp": "webhook-timestamp",
      "webhook-signature": "webhook-signature",
      platformTriggerWebhookEvent: "PlatformTriggerWebhookEvent",
    });
  });

export function platformTriggersCreateTriggerWebhookEventRequestToJSON(
  platformTriggersCreateTriggerWebhookEventRequest:
    PlatformTriggersCreateTriggerWebhookEventRequest,
): string {
  return JSON.stringify(
    PlatformTriggersCreateTriggerWebhookEventRequest$outboundSchema.parse(
      platformTriggersCreateTriggerWebhookEventRequest,
    ),
  );
}
export function platformTriggersCreateTriggerWebhookEventRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PlatformTriggersCreateTriggerWebhookEventRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PlatformTriggersCreateTriggerWebhookEventRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PlatformTriggersCreateTriggerWebhookEventRequest' from JSON`,
  );
}
