/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9325c87699e4
 */

import { expect, test } from "vitest";
import { Glean } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Triggers Platform Triggers Create", async () => {
  const testHttpClient = createTestHTTPClient("platform-triggers-create");

  const glean = new Glean({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiToken: process.env["GLEAN_API_TOKEN"] ?? "value",
  });

  const result = await glean.triggers.create({
    preset_id: "GITHUB_1",
    inputs: {
      "repository": "{repository}",
    },
    delivery: {
      webhook_url: "https://example.com/webhook",
    },
  });
  expect(result).toBeDefined();
});

test("Triggers Platform Triggers List", async () => {
  const testHttpClient = createTestHTTPClient("platform-triggers-list");

  const glean = new Glean({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiToken: process.env["GLEAN_API_TOKEN"] ?? "value",
  });

  const result = await glean.triggers.list();
  expect(result).toBeDefined();
});

test("Triggers Platform Triggers Get", async () => {
  const testHttpClient = createTestHTTPClient("platform-triggers-get");

  const glean = new Glean({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiToken: process.env["GLEAN_API_TOKEN"] ?? "value",
  });

  const result = await glean.triggers.get("<id>");
  expect(result).toBeDefined();
});

test("Triggers Platform Triggers Update", async () => {
  const testHttpClient = createTestHTTPClient("platform-triggers-update");

  const glean = new Glean({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiToken: process.env["GLEAN_API_TOKEN"] ?? "value",
  });

  const result = await glean.triggers.update({
    inputs: {
      "repository": "{repository}",
    },
    delivery: {
      webhook_url: "https://example.com/webhook",
    },
  }, "<id>");
  expect(result).toBeDefined();
});

test("Triggers Platform Triggers Events Search", async () => {
  const testHttpClient = createTestHTTPClient(
    "platform-triggers-events-search",
  );

  const glean = new Glean({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiToken: process.env["GLEAN_API_TOKEN"] ?? "value",
  });

  const result = await glean.triggers.searchEvents("<id>", {});
  expect(result).toBeDefined();
});

test("Triggers Platform Trigger Presets List", async () => {
  const testHttpClient = createTestHTTPClient("platform-trigger-presets-list");

  const glean = new Glean({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiToken: process.env["GLEAN_API_TOKEN"] ?? "value",
  });

  const result = await glean.triggers.listPresets();
  expect(result).toBeDefined();
});

test("Triggers Platform Trigger Presets Get", async () => {
  const testHttpClient = createTestHTTPClient("platform-trigger-presets-get");

  const glean = new Glean({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiToken: process.env["GLEAN_API_TOKEN"] ?? "value",
  });

  const result = await glean.triggers.getPreset("<id>");
  expect(result).toBeDefined();
});

test("Triggers Platform Trigger Presets Input Values List", async () => {
  const testHttpClient = createTestHTTPClient(
    "platform-trigger-presets-input-values-list",
  );

  const glean = new Glean({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiToken: process.env["GLEAN_API_TOKEN"] ?? "value",
  });

  const result = await glean.triggers.listPresetInputValues("<id>", "<value>");
  expect(result).toBeDefined();
});

test("Triggers Platform Trigger Presets Events Search", async () => {
  const testHttpClient = createTestHTTPClient(
    "platform-trigger-presets-events-search",
  );

  const glean = new Glean({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    apiToken: process.env["GLEAN_API_TOKEN"] ?? "value",
  });

  const result = await glean.triggers.searchPresetEvents("<id>", {
    inputs: {
      "repository": "{repository}",
    },
  });
  expect(result).toBeDefined();
});
