/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 16d5d120f477
 */

import { datasourcesGetDatasourceInstanceConfiguration } from "../funcs/datasourcesGetDatasourceInstanceConfiguration.js";
import { datasourcesUpdateDatasourceInstanceConfiguration } from "../funcs/datasourcesUpdateDatasourceInstanceConfiguration.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Datasources extends ClientSDK {
  /**
   * Get datasource instance configuration
   *
   * @remarks
   * Gets the greenlisted configuration values for a datasource instance. Returns only configuration keys that are exposed via the public API greenlist.
   */
  async getDatasourceInstanceConfiguration(
    datasourceId: string,
    instanceId: string,
    options?: RequestOptions,
  ): Promise<components.DatasourceConfigurationResponse> {
    return unwrapAsync(datasourcesGetDatasourceInstanceConfiguration(
      this,
      datasourceId,
      instanceId,
      options,
    ));
  }

  /**
   * Update datasource instance configuration
   *
   * @remarks
   * Updates the greenlisted configuration values for a datasource instance. Only configuration keys that are exposed via the public API greenlist may be set. Returns the full greenlisted configuration after the update is applied.
   */
  async updateDatasourceInstanceConfiguration(
    updateDatasourceConfigurationRequest:
      components.UpdateDatasourceConfigurationRequest,
    datasourceId: string,
    instanceId: string,
    options?: RequestOptions,
  ): Promise<components.DatasourceConfigurationResponse> {
    return unwrapAsync(datasourcesUpdateDatasourceInstanceConfiguration(
      this,
      updateDatasourceConfigurationRequest,
      datasourceId,
      instanceId,
      options,
    ));
  }
}
