/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 71997b5f9b62
 */

import {
  entitiesGetPersonPhoto,
  GetPersonPhotoAcceptEnum,
} from "../funcs/entitiesGetPersonPhoto.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { GetPersonPhotoAcceptEnum } from "../funcs/entitiesGetPersonPhoto.js";

export class Entities extends ClientSDK {
  /**
   * Get person photo
   *
   * @remarks
   * Returns the profile photo bytes for a person whose photo is stored in Glean (crawled from an identity source or user-uploaded via admin console). Photos hosted externally (e.g. Slack CDN) are not served by this endpoint; callers should follow the photoUrl from /people or /listentities directly. Responses include a Cache-Control header (max-age=3600) to reduce redundant fetches.
   */
  async getPersonPhoto(
    personId: string,
    ds?: string | undefined,
    options?: RequestOptions & {
      acceptHeaderOverride?: GetPersonPhotoAcceptEnum;
    },
  ): Promise<operations.GetPersonPhotoResponse> {
    return unwrapAsync(entitiesGetPersonPhoto(
      this,
      personId,
      ds,
      options,
    ));
  }
}
