/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 784571af2f69
 */

import { ClientSDK } from "../lib/sdks.js";
import { Agents } from "./agents.js";
import { Client } from "./client.js";
import { Indexing } from "./indexing.js";
import { Search } from "./search.js";
import { Skills } from "./skills.js";

export class Glean extends ClientSDK {
  private _agents?: Agents;
  get agents(): Agents {
    return (this._agents ??= new Agents(this._options));
  }

  private _skills?: Skills;
  get skills(): Skills {
    return (this._skills ??= new Skills(this._options));
  }

  private _search?: Search;
  get search(): Search {
    return (this._search ??= new Search(this._options));
  }

  private _client?: Client;
  get client(): Client {
    return (this._client ??= new Client(this._options));
  }

  private _indexing?: Indexing;
  get indexing(): Indexing {
    return (this._indexing ??= new Indexing(this._options));
  }
}
