// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3e30b97495c0

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type AuthorizeActionPackRequest struct {
	// ID of the action pack to query or authorize.
	ActionPackID string                                `pathParam:"style=simple,explode=false,name=actionPackId"`
	Body         components.AuthorizeActionPackRequest `request:"mediaType=application/json"`
}

func (o *AuthorizeActionPackRequest) GetActionPackID() string {
	if o == nil {
		return ""
	}
	return o.ActionPackID
}

func (o *AuthorizeActionPackRequest) GetBody() components.AuthorizeActionPackRequest {
	if o == nil {
		return components.AuthorizeActionPackRequest{}
	}
	return o.Body
}

type AuthorizeActionPackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	AuthorizeActionPackResponse *components.AuthorizeActionPackResponse
}

func (o *AuthorizeActionPackResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AuthorizeActionPackResponse) GetAuthorizeActionPackResponse() *components.AuthorizeActionPackResponse {
	if o == nil {
		return nil
	}
	return o.AuthorizeActionPackResponse
}
