// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a5aa85133e31

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateAgentRequest struct {
	// The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
	Locale *string `queryParam:"style=form,explode=true,name=locale"`
	// The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
	TimezoneOffset *int64                           `queryParam:"style=form,explode=true,name=timezoneOffset"`
	Body           components.CreateWorkflowRequest `request:"mediaType=application/json"`
}

func (o *CreateAgentRequest) GetLocale() *string {
	if o == nil {
		return nil
	}
	return o.Locale
}

func (o *CreateAgentRequest) GetTimezoneOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.TimezoneOffset
}

func (o *CreateAgentRequest) GetBody() components.CreateWorkflowRequest {
	if o == nil {
		return components.CreateWorkflowRequest{}
	}
	return o.Body
}

type CreateAgentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	WorkflowResult *components.WorkflowResult
}

func (o *CreateAgentResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAgentResponse) GetWorkflowResult() *components.WorkflowResult {
	if o == nil {
		return nil
	}
	return o.WorkflowResult
}
