// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d71d007cdd54

package operations

import (
	"io"
	"mockserver/internal/sdk/models/components"
)

type GetChatFileRequest struct {
	// Identifier of the chat file to download.
	FileID string `pathParam:"style=simple,explode=false,name=fileId"`
	// When true and the file is a PDF, the response is served inline (Content-Disposition: inline) instead of as an attachment.
	//
	Preview *bool `queryParam:"style=form,explode=true,name=preview"`
}

func (o *GetChatFileRequest) GetFileID() string {
	if o == nil {
		return ""
	}
	return o.FileID
}

func (o *GetChatFileRequest) GetPreview() *bool {
	if o == nil {
		return nil
	}
	return o.Preview
}

type GetChatFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// File content.
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (o *GetChatFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetChatFileResponse) GetResponseStream() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.ResponseStream
}
