// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 485bc76050de

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PlatformAdminUsageSettingsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Updated usage settings.
	PlatformUsageSettingsResponse *components.PlatformUsageSettingsResponse
}

func (o *PlatformAdminUsageSettingsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PlatformAdminUsageSettingsUpdateResponse) GetPlatformUsageSettingsResponse() *components.PlatformUsageSettingsResponse {
	if o == nil {
		return nil
	}
	return o.PlatformUsageSettingsResponse
}
