// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: aed476f89b5e

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PlatformTriggerPresetsGetRequest struct {
	// ID of the preset to retrieve.
	PresetID string `pathParam:"style=simple,explode=false,name=preset_id"`
}

func (o *PlatformTriggerPresetsGetRequest) GetPresetID() string {
	if o == nil {
		return ""
	}
	return o.PresetID
}

type PlatformTriggerPresetsGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response.
	PlatformTriggerPresetGetResponse *components.PlatformTriggerPresetGetResponse
}

func (o *PlatformTriggerPresetsGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PlatformTriggerPresetsGetResponse) GetPlatformTriggerPresetGetResponse() *components.PlatformTriggerPresetGetResponse {
	if o == nil {
		return nil
	}
	return o.PlatformTriggerPresetGetResponse
}
