// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6ae8b05f94b5

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type PlatformTriggersListRequest struct {
	// Maximum number of triggers to return.
	PageSize *int64 `default:"50" queryParam:"style=form,explode=true,name=page_size"`
	// Opaque pagination cursor from a previous response.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (p PlatformTriggersListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformTriggersListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *PlatformTriggersListRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *PlatformTriggersListRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type PlatformTriggersListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response.
	PlatformTriggerListResponse *components.PlatformTriggerListResponse
}

func (o *PlatformTriggersListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PlatformTriggersListResponse) GetPlatformTriggerListResponse() *components.PlatformTriggerListResponse {
	if o == nil {
		return nil
	}
	return o.PlatformTriggerListResponse
}
