// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8531b738e2ad

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PlatformSkillsListRequest struct {
	// Maximum number of skills to return.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page_size"`
	// Opaque pagination cursor from a previous response.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (o *PlatformSkillsListRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *PlatformSkillsListRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

type PlatformSkillsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response.
	PlatformSkillsListResponse *components.PlatformSkillsListResponse
}

func (o *PlatformSkillsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PlatformSkillsListResponse) GetPlatformSkillsListResponse() *components.PlatformSkillsListResponse {
	if o == nil {
		return nil
	}
	return o.PlatformSkillsListResponse
}
