// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7d333b79a0b4

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type PlatformAdminUsageRequestsListRequest struct {
	// Maximum page size; defaults to 20 and cannot exceed 100.
	PageSize *int64 `default:"20" queryParam:"style=form,explode=true,name=page_size"`
	// Opaque continuation bound to filters and current authorization.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Optional structured filters on request status.
	Filters []components.PlatformRequestFilter `queryParam:"serialization=json,name=filters"`
}

func (p PlatformAdminUsageRequestsListRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformAdminUsageRequestsListRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *PlatformAdminUsageRequestsListRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *PlatformAdminUsageRequestsListRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *PlatformAdminUsageRequestsListRequest) GetFilters() []components.PlatformRequestFilter {
	if o == nil {
		return nil
	}
	return o.Filters
}

type PlatformAdminUsageRequestsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A bounded page of authorized requests.
	PlatformRequestListResponse *components.PlatformRequestListResponseUnion
}

func (o *PlatformAdminUsageRequestsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PlatformAdminUsageRequestsListResponse) GetPlatformRequestListResponse() *components.PlatformRequestListResponseUnion {
	if o == nil {
		return nil
	}
	return o.PlatformRequestListResponse
}
