// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d7591a37d7a3

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PlatformChatCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response.
	PlatformChatCompletedResponse *components.PlatformChatCompletedResponse
	// Successful response.
	Res *string
}

func (o *PlatformChatCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PlatformChatCreateResponse) GetPlatformChatCompletedResponse() *components.PlatformChatCompletedResponse {
	if o == nil {
		return nil
	}
	return o.PlatformChatCompletedResponse
}

func (o *PlatformChatCreateResponse) GetRes() *string {
	if o == nil {
		return nil
	}
	return o.Res
}
