// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 040470a330e0

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PostAPIIndexV1BulkindexdocumentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PostAPIIndexV1BulkindexdocumentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
