// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0cc5b155751b

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PostAPIIndexV1IndexemployeeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PostAPIIndexV1IndexemployeeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
