// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 37ba3c8b9a03

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PostAPIIndexV1DeletegroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PostAPIIndexV1DeletegroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
