// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6d83c158e2a4

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PostAPIIndexV1ProcessalldocumentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *PostAPIIndexV1ProcessalldocumentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
