workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Glean API:
        inputs:
            - location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs
        output: .speakeasy/glean-merged-spec.yaml
targets:
    glean:
        target: typescript
        source: Glean API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/glean-el2/sdk/glean-api-specs-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
        testing:
            enabled: true
