/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type AdminsearchRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * Admin search request
   */
  searchRequest: components.SearchRequest;
};

/** @internal */
export type AdminsearchRequest$Outbound = {
  locale?: string | undefined;
  SearchRequest: components.SearchRequest$Outbound;
};

/** @internal */
export const AdminsearchRequest$outboundSchema: z.ZodType<
  AdminsearchRequest$Outbound,
  z.ZodTypeDef,
  AdminsearchRequest
> = z.object({
  locale: z.string().optional(),
  searchRequest: components.SearchRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    searchRequest: "SearchRequest",
  });
});

export function adminsearchRequestToJSON(
  adminsearchRequest: AdminsearchRequest,
): string {
  return JSON.stringify(
    AdminsearchRequest$outboundSchema.parse(adminsearchRequest),
  );
}
