/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type AutocompleteRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * Autocomplete request
   */
  autocompleteRequest: components.AutocompleteRequest;
};

/** @internal */
export type AutocompleteRequest$Outbound = {
  locale?: string | undefined;
  AutocompleteRequest: components.AutocompleteRequest$Outbound;
};

/** @internal */
export const AutocompleteRequest$outboundSchema: z.ZodType<
  AutocompleteRequest$Outbound,
  z.ZodTypeDef,
  AutocompleteRequest
> = z.object({
  locale: z.string().optional(),
  autocompleteRequest: components.AutocompleteRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    autocompleteRequest: "AutocompleteRequest",
  });
});

export function autocompleteRequestToJSON(
  autocompleteRequest: AutocompleteRequest,
): string {
  return JSON.stringify(
    AutocompleteRequest$outboundSchema.parse(autocompleteRequest),
  );
}
