/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ChatStreamRequest = {
  /**
   * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
   */
  timezoneOffset?: number | undefined;
  /**
   * Includes chat history for Glean AI to respond to.
   */
  chatRequest: components.ChatRequest;
};

/** @internal */
export type ChatStreamRequest$Outbound = {
  timezoneOffset?: number | undefined;
  ChatRequest: components.ChatRequest$Outbound;
};

/** @internal */
export const ChatStreamRequest$outboundSchema: z.ZodType<
  ChatStreamRequest$Outbound,
  z.ZodTypeDef,
  ChatStreamRequest
> = z.object({
  timezoneOffset: z.number().int().optional(),
  chatRequest: components.ChatRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    chatRequest: "ChatRequest",
  });
});

export function chatStreamRequestToJSON(
  chatStreamRequest: ChatStreamRequest,
): string {
  return JSON.stringify(
    ChatStreamRequest$outboundSchema.parse(chatStreamRequest),
  );
}
