/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateannouncementRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * Announcement content
   */
  createAnnouncementRequest: components.CreateAnnouncementRequest;
};

/** @internal */
export type CreateannouncementRequest$Outbound = {
  locale?: string | undefined;
  CreateAnnouncementRequest: components.CreateAnnouncementRequest$Outbound;
};

/** @internal */
export const CreateannouncementRequest$outboundSchema: z.ZodType<
  CreateannouncementRequest$Outbound,
  z.ZodTypeDef,
  CreateannouncementRequest
> = z.object({
  locale: z.string().optional(),
  createAnnouncementRequest:
    components.CreateAnnouncementRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createAnnouncementRequest: "CreateAnnouncementRequest",
  });
});

export function createannouncementRequestToJSON(
  createannouncementRequest: CreateannouncementRequest,
): string {
  return JSON.stringify(
    CreateannouncementRequest$outboundSchema.parse(createannouncementRequest),
  );
}
