/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7d0f81696583
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type DeletechatsRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
   */
  timezoneOffset?: number | undefined;
  deleteChatsRequest: components.DeleteChatsRequest;
};

/** @internal */
export type DeletechatsRequest$Outbound = {
  locale?: string | undefined;
  timezoneOffset?: number | undefined;
  DeleteChatsRequest: components.DeleteChatsRequest$Outbound;
};

/** @internal */
export const DeletechatsRequest$outboundSchema: z.ZodType<
  DeletechatsRequest$Outbound,
  z.ZodTypeDef,
  DeletechatsRequest
> = z.object({
  locale: z.string().optional(),
  timezoneOffset: z.number().int().optional(),
  deleteChatsRequest: components.DeleteChatsRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    deleteChatsRequest: "DeleteChatsRequest",
  });
});

export function deletechatsRequestToJSON(
  deletechatsRequest: DeletechatsRequest,
): string {
  return JSON.stringify(
    DeletechatsRequest$outboundSchema.parse(deletechatsRequest),
  );
}
