/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 57bed4c10f6d
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type DeleteanswerRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * DeleteAnswer request
   */
  deleteAnswerRequest: components.DeleteAnswerRequest;
};

/** @internal */
export type DeleteanswerRequest$Outbound = {
  locale?: string | undefined;
  DeleteAnswerRequest: components.DeleteAnswerRequest$Outbound;
};

/** @internal */
export const DeleteanswerRequest$outboundSchema: z.ZodType<
  DeleteanswerRequest$Outbound,
  z.ZodTypeDef,
  DeleteanswerRequest
> = z.object({
  locale: z.string().optional(),
  deleteAnswerRequest: components.DeleteAnswerRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    deleteAnswerRequest: "DeleteAnswerRequest",
  });
});

export function deleteanswerRequestToJSON(
  deleteanswerRequest: DeleteanswerRequest,
): string {
  return JSON.stringify(
    DeleteanswerRequest$outboundSchema.parse(deleteanswerRequest),
  );
}
