/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type EditcollectionitemRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * Edit Collection Items request
   */
  editCollectionItemRequest: components.EditCollectionItemRequest;
};

/** @internal */
export type EditcollectionitemRequest$Outbound = {
  locale?: string | undefined;
  EditCollectionItemRequest: components.EditCollectionItemRequest$Outbound;
};

/** @internal */
export const EditcollectionitemRequest$outboundSchema: z.ZodType<
  EditcollectionitemRequest$Outbound,
  z.ZodTypeDef,
  EditcollectionitemRequest
> = z.object({
  locale: z.string().optional(),
  editCollectionItemRequest:
    components.EditCollectionItemRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    editCollectionItemRequest: "EditCollectionItemRequest",
  });
});

export function editcollectionitemRequestToJSON(
  editcollectionitemRequest: EditcollectionitemRequest,
): string {
  return JSON.stringify(
    EditcollectionitemRequest$outboundSchema.parse(editcollectionitemRequest),
  );
}
