/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4e98c6b5d797
 */

import * as z from "zod/v3";

export type GetAgentSchemasRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
   */
  timezoneOffset?: number | undefined;
  /**
   * The ID of the agent.
   */
  agent_id: string;
};

/** @internal */
export type GetAgentSchemasRequest$Outbound = {
  locale?: string | undefined;
  timezoneOffset?: number | undefined;
  agent_id: string;
};

/** @internal */
export const GetAgentSchemasRequest$outboundSchema: z.ZodType<
  GetAgentSchemasRequest$Outbound,
  z.ZodTypeDef,
  GetAgentSchemasRequest
> = z.object({
  locale: z.string().optional(),
  timezoneOffset: z.number().int().optional(),
  agent_id: z.string(),
});

export function getAgentSchemasRequestToJSON(
  getAgentSchemasRequest: GetAgentSchemasRequest,
): string {
  return JSON.stringify(
    GetAgentSchemasRequest$outboundSchema.parse(getAgentSchemasRequest),
  );
}
