/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 977e694bff37
 */

import * as z from "zod/v3";

export type GetActionAuthStatusRequest = {
  /**
   * ID of the action pack to query or authorize.
   */
  actionPackId: string;
};

/** @internal */
export type GetActionAuthStatusRequest$Outbound = {
  actionPackId: string;
};

/** @internal */
export const GetActionAuthStatusRequest$outboundSchema: z.ZodType<
  GetActionAuthStatusRequest$Outbound,
  z.ZodTypeDef,
  GetActionAuthStatusRequest
> = z.object({
  actionPackId: z.string(),
});

export function getActionAuthStatusRequestToJSON(
  getActionAuthStatusRequest: GetActionAuthStatusRequest,
): string {
  return JSON.stringify(
    GetActionAuthStatusRequest$outboundSchema.parse(getActionAuthStatusRequest),
  );
}
