/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e143e8a37226
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GetchatfilesRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
   */
  timezoneOffset?: number | undefined;
  getChatFilesRequest: components.GetChatFilesRequest;
};

/** @internal */
export type GetchatfilesRequest$Outbound = {
  locale?: string | undefined;
  timezoneOffset?: number | undefined;
  GetChatFilesRequest: components.GetChatFilesRequest$Outbound;
};

/** @internal */
export const GetchatfilesRequest$outboundSchema: z.ZodType<
  GetchatfilesRequest$Outbound,
  z.ZodTypeDef,
  GetchatfilesRequest
> = z.object({
  locale: z.string().optional(),
  timezoneOffset: z.number().int().optional(),
  getChatFilesRequest: components.GetChatFilesRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    getChatFilesRequest: "GetChatFilesRequest",
  });
});

export function getchatfilesRequestToJSON(
  getchatfilesRequest: GetchatfilesRequest,
): string {
  return JSON.stringify(
    GetchatfilesRequest$outboundSchema.parse(getchatfilesRequest),
  );
}
