/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 479f4a76499d
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GetchatapplicationRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
   */
  timezoneOffset?: number | undefined;
  getChatApplicationRequest: components.GetChatApplicationRequest;
};

/** @internal */
export type GetchatapplicationRequest$Outbound = {
  locale?: string | undefined;
  timezoneOffset?: number | undefined;
  GetChatApplicationRequest: components.GetChatApplicationRequest$Outbound;
};

/** @internal */
export const GetchatapplicationRequest$outboundSchema: z.ZodType<
  GetchatapplicationRequest$Outbound,
  z.ZodTypeDef,
  GetchatapplicationRequest
> = z.object({
  locale: z.string().optional(),
  timezoneOffset: z.number().int().optional(),
  getChatApplicationRequest:
    components.GetChatApplicationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    getChatApplicationRequest: "GetChatApplicationRequest",
  });
});

export function getchatapplicationRequestToJSON(
  getchatapplicationRequest: GetchatapplicationRequest,
): string {
  return JSON.stringify(
    GetchatapplicationRequest$outboundSchema.parse(getchatapplicationRequest),
  );
}
