/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetDatasourceInstanceConfigurationRequest = {
  /**
   * The datasource type identifier (e.g. o365sharepoint)
   */
  datasourceId: string;
  /**
   * The datasource instance identifier
   */
  instanceId: string;
};

/** @internal */
export type GetDatasourceInstanceConfigurationRequest$Outbound = {
  datasourceId: string;
  instanceId: string;
};

/** @internal */
export const GetDatasourceInstanceConfigurationRequest$outboundSchema:
  z.ZodType<
    GetDatasourceInstanceConfigurationRequest$Outbound,
    z.ZodTypeDef,
    GetDatasourceInstanceConfigurationRequest
  > = z.object({
    datasourceId: z.string(),
    instanceId: z.string(),
  });

export function getDatasourceInstanceConfigurationRequestToJSON(
  getDatasourceInstanceConfigurationRequest:
    GetDatasourceInstanceConfigurationRequest,
): string {
  return JSON.stringify(
    GetDatasourceInstanceConfigurationRequest$outboundSchema.parse(
      getDatasourceInstanceConfigurationRequest,
    ),
  );
}
