/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 428e91c12ab8
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPersonPhotoRequest = {
  /**
   * The obfuscated ID of the person whose photo to retrieve.
   */
  personId: string;
  /**
   * Optional datasource override for crawled photos (e.g. AZURE, GDRIVE, OKTA). When omitted, the datasource is derived from the person's stored photo URL or the deployment's primary person datasource.
   *
   * @remarks
   */
  ds?: string | undefined;
};

export type GetPersonPhotoResponseResult =
  | ReadableStream<Uint8Array>
  | ReadableStream<Uint8Array>;

export type GetPersonPhotoResponse = {
  headers: { [k: string]: Array<string> };
  result: ReadableStream<Uint8Array> | ReadableStream<Uint8Array>;
};

/** @internal */
export type GetPersonPhotoRequest$Outbound = {
  person_id: string;
  ds?: string | undefined;
};

/** @internal */
export const GetPersonPhotoRequest$outboundSchema: z.ZodType<
  GetPersonPhotoRequest$Outbound,
  z.ZodTypeDef,
  GetPersonPhotoRequest
> = z.object({
  personId: z.string(),
  ds: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    personId: "person_id",
  });
});

export function getPersonPhotoRequestToJSON(
  getPersonPhotoRequest: GetPersonPhotoRequest,
): string {
  return JSON.stringify(
    GetPersonPhotoRequest$outboundSchema.parse(getPersonPhotoRequest),
  );
}

/** @internal */
export const GetPersonPhotoResponseResult$inboundSchema: z.ZodType<
  GetPersonPhotoResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.instanceof(ReadableStream<Uint8Array>),
  z.instanceof(ReadableStream<Uint8Array>),
]);

export function getPersonPhotoResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<GetPersonPhotoResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPersonPhotoResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPersonPhotoResponseResult' from JSON`,
  );
}

/** @internal */
export const GetPersonPhotoResponse$inboundSchema: z.ZodType<
  GetPersonPhotoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(ReadableStream<Uint8Array>),
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function getPersonPhotoResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPersonPhotoResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPersonPhotoResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPersonPhotoResponse' from JSON`,
  );
}
