/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7c1fde5b0804
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ImportAgentRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
   */
  timezoneOffset?: number | undefined;
  /**
   * The ID of the agent to create or update.
   */
  agent_id: string;
  importAgentRequest: components.ImportAgentRequest;
};

/** @internal */
export type ImportAgentRequest$Outbound = {
  locale?: string | undefined;
  timezoneOffset?: number | undefined;
  agent_id: string;
  ImportAgentRequest: components.ImportAgentRequest$Outbound;
};

/** @internal */
export const ImportAgentRequest$outboundSchema: z.ZodType<
  ImportAgentRequest$Outbound,
  z.ZodTypeDef,
  ImportAgentRequest
> = z.object({
  locale: z.string().optional(),
  timezoneOffset: z.number().int().optional(),
  agent_id: z.string(),
  importAgentRequest: components.ImportAgentRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    importAgentRequest: "ImportAgentRequest",
  });
});

export function importAgentRequestToJSON(
  importAgentRequest: ImportAgentRequest,
): string {
  return JSON.stringify(
    ImportAgentRequest$outboundSchema.parse(importAgentRequest),
  );
}
