/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ListanswersRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * ListAnswers request
   */
  listAnswersRequest: components.ListAnswersRequest;
};

/** @internal */
export type ListanswersRequest$Outbound = {
  locale?: string | undefined;
  ListAnswersRequest: components.ListAnswersRequest$Outbound;
};

/** @internal */
export const ListanswersRequest$outboundSchema: z.ZodType<
  ListanswersRequest$Outbound,
  z.ZodTypeDef,
  ListanswersRequest
> = z.object({
  locale: z.string().optional(),
  listAnswersRequest: components.ListAnswersRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    listAnswersRequest: "ListAnswersRequest",
  });
});

export function listanswersRequestToJSON(
  listanswersRequest: ListanswersRequest,
): string {
  return JSON.stringify(
    ListanswersRequest$outboundSchema.parse(listanswersRequest),
  );
}
