/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e34cfd406fd0
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ListentitiesRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * List people request
   */
  listEntitiesRequest: components.ListEntitiesRequest;
};

/** @internal */
export type ListentitiesRequest$Outbound = {
  locale?: string | undefined;
  ListEntitiesRequest: components.ListEntitiesRequest$Outbound;
};

/** @internal */
export const ListentitiesRequest$outboundSchema: z.ZodType<
  ListentitiesRequest$Outbound,
  z.ZodTypeDef,
  ListentitiesRequest
> = z.object({
  locale: z.string().optional(),
  listEntitiesRequest: components.ListEntitiesRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    listEntitiesRequest: "ListEntitiesRequest",
  });
});

export function listentitiesRequestToJSON(
  listentitiesRequest: ListentitiesRequest,
): string {
  return JSON.stringify(
    ListentitiesRequest$outboundSchema.parse(listentitiesRequest),
  );
}
