/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 934fec389517
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type PinRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * Details about the document and query for the pin.
   */
  pinRequest: components.PinRequest;
};

/** @internal */
export type PinRequest$Outbound = {
  locale?: string | undefined;
  PinRequest: components.PinRequest$Outbound;
};

/** @internal */
export const PinRequest$outboundSchema: z.ZodType<
  PinRequest$Outbound,
  z.ZodTypeDef,
  PinRequest
> = z.object({
  locale: z.string().optional(),
  pinRequest: components.PinRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    pinRequest: "PinRequest",
  });
});

export function pinRequestToJSON(pinRequest: PinRequest): string {
  return JSON.stringify(PinRequest$outboundSchema.parse(pinRequest));
}
