/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 49839848ed07
 */

import * as z from "zod/v3";

export type PlatformAgentsGetRunRequest = {
  /**
   * ID of the agent that owns the run.
   */
  agent_id: string;
  /**
   * ID of the durable run to retrieve.
   */
  run_id: string;
};

/** @internal */
export type PlatformAgentsGetRunRequest$Outbound = {
  agent_id: string;
  run_id: string;
};

/** @internal */
export const PlatformAgentsGetRunRequest$outboundSchema: z.ZodType<
  PlatformAgentsGetRunRequest$Outbound,
  z.ZodTypeDef,
  PlatformAgentsGetRunRequest
> = z.object({
  agent_id: z.string(),
  run_id: z.string(),
});

export function platformAgentsGetRunRequestToJSON(
  platformAgentsGetRunRequest: PlatformAgentsGetRunRequest,
): string {
  return JSON.stringify(
    PlatformAgentsGetRunRequest$outboundSchema.parse(
      platformAgentsGetRunRequest,
    ),
  );
}
