/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9b2ebcd4fdc0
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";

export type PlatformUsageRequestsListRequest = {
  /**
   * Maximum page size; defaults to 20 and cannot exceed 100.
   */
  page_size?: number | undefined;
  /**
   * Opaque continuation bound to filters and current authorization.
   */
  cursor?: string | undefined;
  /**
   * Optional structured filters on request status.
   */
  filters?: Array<components.PlatformRequestFilter> | undefined;
};

/** @internal */
export type PlatformUsageRequestsListRequest$Outbound = {
  page_size: number;
  cursor?: string | undefined;
  filters?: Array<components.PlatformRequestFilter$Outbound> | undefined;
};

/** @internal */
export const PlatformUsageRequestsListRequest$outboundSchema: z.ZodType<
  PlatformUsageRequestsListRequest$Outbound,
  z.ZodTypeDef,
  PlatformUsageRequestsListRequest
> = z.object({
  page_size: z.number().int().default(20),
  cursor: z.string().optional(),
  filters: z.array(components.PlatformRequestFilter$outboundSchema).optional(),
});

export function platformUsageRequestsListRequestToJSON(
  platformUsageRequestsListRequest: PlatformUsageRequestsListRequest,
): string {
  return JSON.stringify(
    PlatformUsageRequestsListRequest$outboundSchema.parse(
      platformUsageRequestsListRequest,
    ),
  );
}
