/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5689f4ee466e
 */

import * as z from "zod/v3";

export type PlatformTriggersDeleteRequest = {
  /**
   * ID of the trigger to delete.
   */
  trigger_id: string;
};

/** @internal */
export type PlatformTriggersDeleteRequest$Outbound = {
  trigger_id: string;
};

/** @internal */
export const PlatformTriggersDeleteRequest$outboundSchema: z.ZodType<
  PlatformTriggersDeleteRequest$Outbound,
  z.ZodTypeDef,
  PlatformTriggersDeleteRequest
> = z.object({
  trigger_id: z.string(),
});

export function platformTriggersDeleteRequestToJSON(
  platformTriggersDeleteRequest: PlatformTriggersDeleteRequest,
): string {
  return JSON.stringify(
    PlatformTriggersDeleteRequest$outboundSchema.parse(
      platformTriggersDeleteRequest,
    ),
  );
}
