/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 40fe427dde80
 */

import * as z from "zod/v3";

export type PlatformSearchFiltersRequest = {
  /**
   * Restrict metadata to one or more canonical normalized datasource identifiers. With a nonblank `query`, exactly one datasource is required.
   *
   * @remarks
   */
  datasources?: Array<string> | undefined;
  /**
   * Optional search query used to request bounded facet values for the selected datasource. When present it must be nonblank.
   *
   * @remarks
   */
  query?: string | undefined;
};

/** @internal */
export type PlatformSearchFiltersRequest$Outbound = {
  datasources?: Array<string> | undefined;
  query?: string | undefined;
};

/** @internal */
export const PlatformSearchFiltersRequest$outboundSchema: z.ZodType<
  PlatformSearchFiltersRequest$Outbound,
  z.ZodTypeDef,
  PlatformSearchFiltersRequest
> = z.object({
  datasources: z.array(z.string()).optional(),
  query: z.string().optional(),
});

export function platformSearchFiltersRequestToJSON(
  platformSearchFiltersRequest: PlatformSearchFiltersRequest,
): string {
  return JSON.stringify(
    PlatformSearchFiltersRequest$outboundSchema.parse(
      platformSearchFiltersRequest,
    ),
  );
}
