/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fa69fa99c2eb
 */

import * as z from "zod/v3";

export type PlatformTriggerPresetsGetRequest = {
  /**
   * ID of the preset to retrieve.
   */
  preset_id: string;
};

/** @internal */
export type PlatformTriggerPresetsGetRequest$Outbound = {
  preset_id: string;
};

/** @internal */
export const PlatformTriggerPresetsGetRequest$outboundSchema: z.ZodType<
  PlatformTriggerPresetsGetRequest$Outbound,
  z.ZodTypeDef,
  PlatformTriggerPresetsGetRequest
> = z.object({
  preset_id: z.string(),
});

export function platformTriggerPresetsGetRequestToJSON(
  platformTriggerPresetsGetRequest: PlatformTriggerPresetsGetRequest,
): string {
  return JSON.stringify(
    PlatformTriggerPresetsGetRequest$outboundSchema.parse(
      platformTriggerPresetsGetRequest,
    ),
  );
}
