/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f83cfd7f2d50
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PlatformSkillsGetContentRequest = {
  /**
   * Glean skill ID.
   */
  skill_id: string;
};

export type PlatformSkillsGetContentResponse = {
  Headers: { [k: string]: Array<string> };
  result: ReadableStream<Uint8Array>;
};

/** @internal */
export type PlatformSkillsGetContentRequest$Outbound = {
  skill_id: string;
};

/** @internal */
export const PlatformSkillsGetContentRequest$outboundSchema: z.ZodType<
  PlatformSkillsGetContentRequest$Outbound,
  z.ZodTypeDef,
  PlatformSkillsGetContentRequest
> = z.object({
  skill_id: z.string(),
});

export function platformSkillsGetContentRequestToJSON(
  platformSkillsGetContentRequest: PlatformSkillsGetContentRequest,
): string {
  return JSON.stringify(
    PlatformSkillsGetContentRequest$outboundSchema.parse(
      platformSkillsGetContentRequest,
    ),
  );
}

/** @internal */
export const PlatformSkillsGetContentResponse$inboundSchema: z.ZodType<
  PlatformSkillsGetContentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.instanceof(ReadableStream<Uint8Array>),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function platformSkillsGetContentResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlatformSkillsGetContentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformSkillsGetContentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformSkillsGetContentResponse' from JSON`,
  );
}
