/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9b6836e5a5d9
 */

import * as z from "zod/v3";

export type PlatformSkillsPreviewSourceRequest = {
  /**
   * GitHub URL for a skill directory, SKILL.md file, or repository to inspect.
   */
  source_url: string;
  stream?: false | undefined;
};

/** @internal */
export type PlatformSkillsPreviewSourceRequest$Outbound = {
  source_url: string;
  stream: false;
};

/** @internal */
export const PlatformSkillsPreviewSourceRequest$outboundSchema: z.ZodType<
  PlatformSkillsPreviewSourceRequest$Outbound,
  z.ZodTypeDef,
  PlatformSkillsPreviewSourceRequest
> = z.object({
  source_url: z.string(),
  stream: z.literal(false).default(false as const),
});

export function platformSkillsPreviewSourceRequestToJSON(
  platformSkillsPreviewSourceRequest: PlatformSkillsPreviewSourceRequest,
): string {
  return JSON.stringify(
    PlatformSkillsPreviewSourceRequest$outboundSchema.parse(
      platformSkillsPreviewSourceRequest,
    ),
  );
}
