/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 62f7c1070208
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export const PutRestApiIndexDocumentDocIdCustomMetadataGroupNameServerList = [
  "https://{instance}-be.glean.com",
] as const;

export type PutRestApiIndexDocumentDocIdCustomMetadataGroupNameRequest = {
  /**
   * Unique Glean identifier of the document
   */
  docId: string;
  /**
   * Name of the metadata group as specified while adding schema
   */
  groupName: string;
  customMetadataPutRequest: components.CustomMetadataPutRequest;
};

/** @internal */
export type PutRestApiIndexDocumentDocIdCustomMetadataGroupNameRequest$Outbound =
  {
    docId: string;
    groupName: string;
    CustomMetadataPutRequest: components.CustomMetadataPutRequest$Outbound;
  };

/** @internal */
export const PutRestApiIndexDocumentDocIdCustomMetadataGroupNameRequest$outboundSchema:
  z.ZodType<
    PutRestApiIndexDocumentDocIdCustomMetadataGroupNameRequest$Outbound,
    z.ZodTypeDef,
    PutRestApiIndexDocumentDocIdCustomMetadataGroupNameRequest
  > = z.object({
    docId: z.string(),
    groupName: z.string(),
    customMetadataPutRequest:
      components.CustomMetadataPutRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      customMetadataPutRequest: "CustomMetadataPutRequest",
    });
  });

export function putRestApiIndexDocumentDocIdCustomMetadataGroupNameRequestToJSON(
  putRestApiIndexDocumentDocIdCustomMetadataGroupNameRequest:
    PutRestApiIndexDocumentDocIdCustomMetadataGroupNameRequest,
): string {
  return JSON.stringify(
    PutRestApiIndexDocumentDocIdCustomMetadataGroupNameRequest$outboundSchema
      .parse(putRestApiIndexDocumentDocIdCustomMetadataGroupNameRequest),
  );
}
