/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d185d699125a
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type RotateDatasourceCredentialsRequest = {
  /**
   * The full datasource instance identifier (e.g. o365sharepoint_abc123)
   */
  datasourceInstanceId: string;
  rotateDatasourceCredentialsRequest:
    components.RotateDatasourceCredentialsRequest;
};

/** @internal */
export type RotateDatasourceCredentialsRequest$Outbound = {
  datasourceInstanceId: string;
  RotateDatasourceCredentialsRequest:
    components.RotateDatasourceCredentialsRequest$Outbound;
};

/** @internal */
export const RotateDatasourceCredentialsRequest$outboundSchema: z.ZodType<
  RotateDatasourceCredentialsRequest$Outbound,
  z.ZodTypeDef,
  RotateDatasourceCredentialsRequest
> = z.object({
  datasourceInstanceId: z.string(),
  rotateDatasourceCredentialsRequest:
    components.RotateDatasourceCredentialsRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    rotateDatasourceCredentialsRequest: "RotateDatasourceCredentialsRequest",
  });
});

export function rotateDatasourceCredentialsRequestToJSON(
  rotateDatasourceCredentialsRequest: RotateDatasourceCredentialsRequest,
): string {
  return JSON.stringify(
    RotateDatasourceCredentialsRequest$outboundSchema.parse(
      rotateDatasourceCredentialsRequest,
    ),
  );
}
