/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b6b564ec18ac
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdatepolicyRequest = {
  /**
   * The id of the policy to fetch.
   */
  id: string;
  updateDlpReportRequest: components.UpdateDlpReportRequest;
};

/** @internal */
export type UpdatepolicyRequest$Outbound = {
  id: string;
  UpdateDlpReportRequest: components.UpdateDlpReportRequest$Outbound;
};

/** @internal */
export const UpdatepolicyRequest$outboundSchema: z.ZodType<
  UpdatepolicyRequest$Outbound,
  z.ZodTypeDef,
  UpdatepolicyRequest
> = z.object({
  id: z.string(),
  updateDlpReportRequest: components.UpdateDlpReportRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateDlpReportRequest: "UpdateDlpReportRequest",
  });
});

export function updatepolicyRequestToJSON(
  updatepolicyRequest: UpdatepolicyRequest,
): string {
  return JSON.stringify(
    UpdatepolicyRequest$outboundSchema.parse(updatepolicyRequest),
  );
}
