/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2bfdbe94db50
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UploadchatfilesRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * The offset of the client's timezone in minutes from UTC. e.g. PDT is -420 because it's 7 hours behind UTC.
   */
  timezoneOffset?: number | undefined;
  uploadChatFilesRequest: components.UploadChatFilesRequest;
};

/** @internal */
export type UploadchatfilesRequest$Outbound = {
  locale?: string | undefined;
  timezoneOffset?: number | undefined;
  UploadChatFilesRequest: components.UploadChatFilesRequest$Outbound;
};

/** @internal */
export const UploadchatfilesRequest$outboundSchema: z.ZodType<
  UploadchatfilesRequest$Outbound,
  z.ZodTypeDef,
  UploadchatfilesRequest
> = z.object({
  locale: z.string().optional(),
  timezoneOffset: z.number().int().optional(),
  uploadChatFilesRequest: components.UploadChatFilesRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    uploadChatFilesRequest: "UploadChatFilesRequest",
  });
});

export function uploadchatfilesRequestToJSON(
  uploadchatfilesRequest: UploadchatfilesRequest,
): string {
  return JSON.stringify(
    UploadchatfilesRequest$outboundSchema.parse(uploadchatfilesRequest),
  );
}
