/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type VerifyRequest = {
  /**
   * The client's preferred locale in rfc5646 format (e.g. `en`, `ja`, `pt-BR`). If omitted, the `Accept-Language` will be used. If not present or not supported, defaults to the closest match or `en`.
   */
  locale?: string | undefined;
  /**
   * Details about the verification request.
   */
  verifyRequest: components.VerifyRequest;
};

/** @internal */
export type VerifyRequest$Outbound = {
  locale?: string | undefined;
  VerifyRequest: components.VerifyRequest$Outbound;
};

/** @internal */
export const VerifyRequest$outboundSchema: z.ZodType<
  VerifyRequest$Outbound,
  z.ZodTypeDef,
  VerifyRequest
> = z.object({
  locale: z.string().optional(),
  verifyRequest: components.VerifyRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    verifyRequest: "VerifyRequest",
  });
});

export function verifyRequestToJSON(verifyRequest: VerifyRequest): string {
  return JSON.stringify(VerifyRequest$outboundSchema.parse(verifyRequest));
}
