// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 58037ce7bcc2

package components

import (
	"encoding/json"
	"fmt"
)

// ArtifactType - Type of the Artifact
type ArtifactType string

const (
	ArtifactTypePaper    ArtifactType = "PAPER"
	ArtifactTypeAgent    ArtifactType = "AGENT"
	ArtifactTypeMessage  ArtifactType = "MESSAGE"
	ArtifactTypeEmail    ArtifactType = "EMAIL"
	ArtifactTypeHTMLCode ArtifactType = "HTML_CODE"
	ArtifactTypeSlide    ArtifactType = "SLIDE"
)

func (e ArtifactType) ToPointer() *ArtifactType {
	return &e
}
func (e *ArtifactType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PAPER":
		fallthrough
	case "AGENT":
		fallthrough
	case "MESSAGE":
		fallthrough
	case "EMAIL":
		fallthrough
	case "HTML_CODE":
		fallthrough
	case "SLIDE":
		*e = ArtifactType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ArtifactType: %v", v)
	}
}
