// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3c484355e817

package components

// GreenlistUsersRequest - Describes the request body of the /betausers API call
type GreenlistUsersRequest struct {
	// Datasource which needs to be made visible to users specified in the `emails` field.
	Datasource string `json:"datasource"`
	// The emails of the beta users
	Emails []string `json:"emails"`
}

func (o *GreenlistUsersRequest) GetDatasource() string {
	if o == nil {
		return ""
	}
	return o.Datasource
}

func (o *GreenlistUsersRequest) GetEmails() []string {
	if o == nil {
		return []string{}
	}
	return o.Emails
}
