// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 335d40d15f4d

package components

type Hotword struct {
	Regex     *string           `json:"regex,omitempty"`
	Proximity *HotwordProximity `json:"proximity,omitempty"`
}

func (o *Hotword) GetRegex() *string {
	if o == nil {
		return nil
	}
	return o.Regex
}

func (o *Hotword) GetProximity() *HotwordProximity {
	if o == nil {
		return nil
	}
	return o.Proximity
}
