// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 03e6e6a18fa1

package components

type ListDlpReportsResponse struct {
	Reports []DlpReport `json:"reports,omitempty"`
}

func (o *ListDlpReportsResponse) GetReports() []DlpReport {
	if o == nil {
		return nil
	}
	return o.Reports
}
