// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1cb76a7bd475

package components

type McpHostApplicationBreakdown struct {
	// Host application name.
	HostApplication *string `json:"hostApplication,omitempty"`
	// Total number of MCP calls made from this host application in the specified time period.
	TotalCalls *int64 `json:"totalCalls,omitempty"`
	// Total number of active users from this host application in the specified time period.
	ActiveUsers *int64 `json:"activeUsers,omitempty"`
}

func (o *McpHostApplicationBreakdown) GetHostApplication() *string {
	if o == nil {
		return nil
	}
	return o.HostApplication
}

func (o *McpHostApplicationBreakdown) GetTotalCalls() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCalls
}

func (o *McpHostApplicationBreakdown) GetActiveUsers() *int64 {
	if o == nil {
		return nil
	}
	return o.ActiveUsers
}
