// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 74264019ae56

package components

type McpToolBreakdown struct {
	// MCP tool name.
	Tool *string `json:"tool,omitempty"`
	// Total number of MCP calls for this tool in the specified time period.
	TotalCalls *int64 `json:"totalCalls,omitempty"`
	// Total number of active users for this tool in the specified time period.
	ActiveUsers *int64 `json:"activeUsers,omitempty"`
	// Host applications using this tool in the specified time period.
	HostApplications []string `json:"hostApplications,omitempty"`
}

func (o *McpToolBreakdown) GetTool() *string {
	if o == nil {
		return nil
	}
	return o.Tool
}

func (o *McpToolBreakdown) GetTotalCalls() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCalls
}

func (o *McpToolBreakdown) GetActiveUsers() *int64 {
	if o == nil {
		return nil
	}
	return o.ActiveUsers
}

func (o *McpToolBreakdown) GetHostApplications() []string {
	if o == nil {
		return nil
	}
	return o.HostApplications
}
