// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 81cb594b3436

package components

// PlatformFilter - A single filter criterion. For `EQUALS`, multiple values within a filter are OR'd. For `NOT_EQUALS`, multiple values exclude all listed values. Filters are AND'd with each other and with any inline query operators.
type PlatformFilter struct {
	// The field to filter on. Accepts built-in filter field names such as `type`, `owner`, `from`, `author`, `channel`, `status`, `assignee`, `reporter`, `component`, `mentions`, and `collection`, plus custom datasource property names.
	//
	Field string `json:"field"`
	// One or more values to match.
	Values []string `json:"values"`
	// Comparison operator to apply to this filter. Defaults to `EQUALS`. `GT`, `GTE`, `LT`, and `LTE` range operators require exactly one value; express bounded ranges with multiple filters on the same field.
	//
	Operator *PlatformFilterOperator `json:"operator,omitempty"`
}

func (o *PlatformFilter) GetField() string {
	if o == nil {
		return ""
	}
	return o.Field
}

func (o *PlatformFilter) GetValues() []string {
	if o == nil {
		return []string{}
	}
	return o.Values
}

func (o *PlatformFilter) GetOperator() *PlatformFilterOperator {
	if o == nil {
		return nil
	}
	return o.Operator
}
