// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dc15eae8b625

package components

type PlatformSkillSourcePreview struct {
	// Skill name parsed from SKILL.md frontmatter.
	DisplayName string `json:"display_name"`
	// Skill description parsed from SKILL.md frontmatter.
	Description string `json:"description"`
	// Resolved URL for this skill within the source.
	SourceURL string `json:"source_url"`
	// Commit SHA used to produce the preview.
	CommitSha string `json:"commit_sha"`
	// SKILL.md content fetched as part of the preview.
	MainContent string `json:"main_content"`
	// Supporting files fetched with the skill.
	Files []PlatformSkillSourcePreviewFile `json:"files"`
	// Relative paths discovered for the skill.
	FileTree []string `json:"file_tree"`
}

func (o *PlatformSkillSourcePreview) GetDisplayName() string {
	if o == nil {
		return ""
	}
	return o.DisplayName
}

func (o *PlatformSkillSourcePreview) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *PlatformSkillSourcePreview) GetSourceURL() string {
	if o == nil {
		return ""
	}
	return o.SourceURL
}

func (o *PlatformSkillSourcePreview) GetCommitSha() string {
	if o == nil {
		return ""
	}
	return o.CommitSha
}

func (o *PlatformSkillSourcePreview) GetMainContent() string {
	if o == nil {
		return ""
	}
	return o.MainContent
}

func (o *PlatformSkillSourcePreview) GetFiles() []PlatformSkillSourcePreviewFile {
	if o == nil {
		return []PlatformSkillSourcePreviewFile{}
	}
	return o.Files
}

func (o *PlatformSkillSourcePreview) GetFileTree() []string {
	if o == nil {
		return []string{}
	}
	return o.FileTree
}
