// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 25016540ff2e

package components

type PlatformTriggerPresetListResponse struct {
	// Trigger presets available to the caller.
	Results []PlatformTriggerPreset `json:"results"`
	// Whether additional results are available.
	HasMore bool `json:"has_more"`
	// Cursor for the next page, or null when no more results are available.
	NextCursor *string `json:"next_cursor"`
	// Platform-generated request ID for support correlation.
	RequestID string `json:"request_id"`
}

func (o *PlatformTriggerPresetListResponse) GetResults() []PlatformTriggerPreset {
	if o == nil {
		return []PlatformTriggerPreset{}
	}
	return o.Results
}

func (o *PlatformTriggerPresetListResponse) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *PlatformTriggerPresetListResponse) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *PlatformTriggerPresetListResponse) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}
