// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 27e43bc64103

package components

import (
	"mockserver/internal/sdk/utils"
)

type PlatformSkillSourcePreviewFile struct {
	// Relative path within the skill bundle.
	Path string `json:"path"`
	// UTF-8 file content.
	Content string `json:"content"`
}

func (p PlatformSkillSourcePreviewFile) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSkillSourcePreviewFile) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"path", "content"}); err != nil {
		return err
	}
	return nil
}

func (o *PlatformSkillSourcePreviewFile) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *PlatformSkillSourcePreviewFile) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}
