// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 69a989d8c41e

package components

import (
	"encoding/json"
	"fmt"
)

// PlatformFilterOperator - Supported filter operator.
type PlatformFilterOperator string

const (
	PlatformFilterOperatorEquals    PlatformFilterOperator = "EQUALS"
	PlatformFilterOperatorNotEquals PlatformFilterOperator = "NOT_EQUALS"
	PlatformFilterOperatorGt        PlatformFilterOperator = "GT"
	PlatformFilterOperatorGte       PlatformFilterOperator = "GTE"
	PlatformFilterOperatorLt        PlatformFilterOperator = "LT"
	PlatformFilterOperatorLte       PlatformFilterOperator = "LTE"
)

func (e PlatformFilterOperator) ToPointer() *PlatformFilterOperator {
	return &e
}
func (e *PlatformFilterOperator) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EQUALS":
		fallthrough
	case "NOT_EQUALS":
		fallthrough
	case "GT":
		fallthrough
	case "GTE":
		fallthrough
	case "LT":
		fallthrough
	case "LTE":
		*e = PlatformFilterOperator(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlatformFilterOperator: %v", v)
	}
}
