// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8c217f4e9ded

package components

type PlatformSkillVersionGetResponse struct {
	Version PlatformSkillVersion `json:"version"`
	// Platform-generated request ID for support correlation.
	RequestID string `json:"request_id"`
}

func (o *PlatformSkillVersionGetResponse) GetVersion() PlatformSkillVersion {
	if o == nil {
		return PlatformSkillVersion{}
	}
	return o.Version
}

func (o *PlatformSkillVersionGetResponse) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}
