// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 12530e23bf37

package components

type PlatformMessageInput struct {
	// Role of the message author.
	Role PlatformMessageRole `json:"role"`
	// Content blocks in the message.
	Content []PlatformMessageTextBlockInput `json:"content"`
}

func (o *PlatformMessageInput) GetRole() PlatformMessageRole {
	if o == nil {
		return PlatformMessageRole("")
	}
	return o.Role
}

func (o *PlatformMessageInput) GetContent() []PlatformMessageTextBlockInput {
	if o == nil {
		return []PlatformMessageTextBlockInput{}
	}
	return o.Content
}
