// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 898cd6d763b8

package components

import (
	"io"
)

type PlatformSkillVersionCreateRequestFile struct {
	FileName string    `multipartForm:"name=fileName"`
	Content  io.Reader `multipartForm:"content"`
}

func (o *PlatformSkillVersionCreateRequestFile) GetFileName() string {
	if o == nil {
		return ""
	}
	return o.FileName
}

func (o *PlatformSkillVersionCreateRequestFile) GetContent() io.Reader {
	if o == nil {
		return nil
	}
	return o.Content
}

type PlatformSkillVersionCreateRequest struct {
	// SKILL.md, .zip, or .skill bundle to store as a new version.
	File PlatformSkillVersionCreateRequestFile `multipartForm:"file,name=file"`
}

func (o *PlatformSkillVersionCreateRequest) GetFile() PlatformSkillVersionCreateRequestFile {
	if o == nil {
		return PlatformSkillVersionCreateRequestFile{}
	}
	return o.File
}
