// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 85ec91ec5850

package components

import (
	"encoding/json"
	"fmt"
)

// PlatformRequestStatus - Stored request state.
type PlatformRequestStatus string

const (
	PlatformRequestStatusPending  PlatformRequestStatus = "PENDING"
	PlatformRequestStatusApproved PlatformRequestStatus = "APPROVED"
	PlatformRequestStatusDenied   PlatformRequestStatus = "DENIED"
)

func (e PlatformRequestStatus) ToPointer() *PlatformRequestStatus {
	return &e
}
func (e *PlatformRequestStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PENDING":
		fallthrough
	case "APPROVED":
		fallthrough
	case "DENIED":
		*e = PlatformRequestStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlatformRequestStatus: %v", v)
	}
}
