// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 44e295f29630

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
)

// BusinessJustification - Whether a business justification is required when requesting a usage limit increase.
type BusinessJustification string

const (
	BusinessJustificationOptional BusinessJustification = "OPTIONAL"
	BusinessJustificationRequired BusinessJustification = "REQUIRED"
)

func (e BusinessJustification) ToPointer() *BusinessJustification {
	return &e
}
func (e *BusinessJustification) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OPTIONAL":
		fallthrough
	case "REQUIRED":
		*e = BusinessJustification(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BusinessJustification: %v", v)
	}
}

// PlatformLimitIncreaseRequestSettings - Settings that govern usage limit increase requests.
type PlatformLimitIncreaseRequestSettings struct {
	// Whether a business justification is required when requesting a usage limit increase.
	//
	BusinessJustification BusinessJustification `json:"business_justification"`
}

func (p PlatformLimitIncreaseRequestSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformLimitIncreaseRequestSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"business_justification"}); err != nil {
		return err
	}
	return nil
}

func (o *PlatformLimitIncreaseRequestSettings) GetBusinessJustification() BusinessJustification {
	if o == nil {
		return BusinessJustification("")
	}
	return o.BusinessJustification
}
