// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 894f1f95fef3

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
)

// PlatformChatJSONSchemaFormatType - Discriminator. Must be JSON_SCHEMA.
type PlatformChatJSONSchemaFormatType string

const (
	PlatformChatJSONSchemaFormatTypeJSONSchema PlatformChatJSONSchemaFormatType = "JSON_SCHEMA"
)

func (e PlatformChatJSONSchemaFormatType) ToPointer() *PlatformChatJSONSchemaFormatType {
	return &e
}
func (e *PlatformChatJSONSchemaFormatType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "JSON_SCHEMA":
		*e = PlatformChatJSONSchemaFormatType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlatformChatJSONSchemaFormatType: %v", v)
	}
}

// PlatformChatJSONSchemaFormat - Constrains the assistant response to a caller-supplied JSON Schema.
type PlatformChatJSONSchemaFormat struct {
	// Discriminator. Must be JSON_SCHEMA.
	Type PlatformChatJSONSchemaFormatType `json:"type"`
	// A stable identifier for the schema.
	Name string `json:"name"`
	// An optional human-readable description of the schema.
	Description *string `json:"description,omitempty"`
	// A JSON Schema object describing the desired output shape.
	Schema map[string]any `json:"schema"`
	// When true, the provider validates the response against the schema. Unsupported by some providers; defaults to true.
	//
	Strict *bool `default:"true" json:"strict"`
}

func (p PlatformChatJSONSchemaFormat) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformChatJSONSchemaFormat) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"type", "name", "schema"}); err != nil {
		return err
	}
	return nil
}

func (o *PlatformChatJSONSchemaFormat) GetType() PlatformChatJSONSchemaFormatType {
	if o == nil {
		return PlatformChatJSONSchemaFormatType("")
	}
	return o.Type
}

func (o *PlatformChatJSONSchemaFormat) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PlatformChatJSONSchemaFormat) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PlatformChatJSONSchemaFormat) GetSchema() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.Schema
}

func (o *PlatformChatJSONSchemaFormat) GetStrict() *bool {
	if o == nil {
		return nil
	}
	return o.Strict
}
