// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b552320b1b9f

package components

// PlatformUserDepartment - The department that a user belongs to.
type PlatformUserDepartment struct {
	// Opaque department ID. A renamed department gets a new ID.
	DepartmentID string `json:"department_id"`
	// Department name.
	DisplayName string `json:"display_name"`
}

func (o *PlatformUserDepartment) GetDepartmentID() string {
	if o == nil {
		return ""
	}
	return o.DepartmentID
}

func (o *PlatformUserDepartment) GetDisplayName() string {
	if o == nil {
		return ""
	}
	return o.DisplayName
}
