// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c90d8c08b7f1

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
)

// PlatformSkillSourcePreviewStreamProgressType - Event type, also sent as the SSE `event` name.
type PlatformSkillSourcePreviewStreamProgressType string

const (
	PlatformSkillSourcePreviewStreamProgressTypeProgress PlatformSkillSourcePreviewStreamProgressType = "PROGRESS"
)

func (e PlatformSkillSourcePreviewStreamProgressType) ToPointer() *PlatformSkillSourcePreviewStreamProgressType {
	return &e
}
func (e *PlatformSkillSourcePreviewStreamProgressType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PROGRESS":
		*e = PlatformSkillSourcePreviewStreamProgressType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlatformSkillSourcePreviewStreamProgressType: %v", v)
	}
}

// PlatformSkillSourcePreviewStreamProgress - One skill finished inspecting; names the skill in progress.
type PlatformSkillSourcePreviewStreamProgress struct {
	// Event type, also sent as the SSE `event` name.
	Type PlatformSkillSourcePreviewStreamProgressType `json:"type"`
	// Number of skills inspected so far.
	Completed int64 `json:"completed"`
	// Number of skills to inspect.
	Total int64 `json:"total"`
	// Path of the skill being inspected.
	CurrentSkill string `json:"current_skill"`
}

func (p PlatformSkillSourcePreviewStreamProgress) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSkillSourcePreviewStreamProgress) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"type", "completed", "total", "current_skill"}); err != nil {
		return err
	}
	return nil
}

func (o *PlatformSkillSourcePreviewStreamProgress) GetType() PlatformSkillSourcePreviewStreamProgressType {
	if o == nil {
		return PlatformSkillSourcePreviewStreamProgressType("")
	}
	return o.Type
}

func (o *PlatformSkillSourcePreviewStreamProgress) GetCompleted() int64 {
	if o == nil {
		return 0
	}
	return o.Completed
}

func (o *PlatformSkillSourcePreviewStreamProgress) GetTotal() int64 {
	if o == nil {
		return 0
	}
	return o.Total
}

func (o *PlatformSkillSourcePreviewStreamProgress) GetCurrentSkill() string {
	if o == nil {
		return ""
	}
	return o.CurrentSkill
}
