// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a2106a7f5d0d

package components

type PlatformAgentGetResponse struct {
	Agent PlatformAgent `json:"agent"`
	// Platform-generated request ID for support correlation.
	RequestID string `json:"request_id"`
}

func (o *PlatformAgentGetResponse) GetAgent() PlatformAgent {
	if o == nil {
		return PlatformAgent{}
	}
	return o.Agent
}

func (o *PlatformAgentGetResponse) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}
