// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9348b7a0ba5c

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type PlatformSkill struct {
	// Glean skill ID.
	ID string `json:"id"`
	// Human-readable skill name.
	DisplayName string `json:"display_name"`
	// Human-readable skill description.
	Description string `json:"description"`
	// Latest major version number for the skill.
	LatestVersion int64 `json:"latest_version"`
	// Latest minor version number for the skill.
	LatestMinorVersion int64 `json:"latest_minor_version"`
	// Current skill status.
	Status PlatformSkillStatus `json:"status"`
	// Source category for the skill.
	Origin           PlatformSkillOrigin            `json:"origin"`
	SourceProvenance *PlatformSkillSourceProvenance `json:"source_provenance,omitempty"`
	// A lightweight reference to a person, used where a payload merely points at someone.
	Owner PlatformPersonReference `json:"owner"`
	// Time the skill was created.
	CreatedAt time.Time `json:"created_at"`
	// Time the skill was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

func (p PlatformSkill) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSkill) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"id", "display_name", "description", "latest_version", "latest_minor_version", "status", "origin", "owner", "created_at", "updated_at"}); err != nil {
		return err
	}
	return nil
}

func (o *PlatformSkill) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PlatformSkill) GetDisplayName() string {
	if o == nil {
		return ""
	}
	return o.DisplayName
}

func (o *PlatformSkill) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *PlatformSkill) GetLatestVersion() int64 {
	if o == nil {
		return 0
	}
	return o.LatestVersion
}

func (o *PlatformSkill) GetLatestMinorVersion() int64 {
	if o == nil {
		return 0
	}
	return o.LatestMinorVersion
}

func (o *PlatformSkill) GetStatus() PlatformSkillStatus {
	if o == nil {
		return PlatformSkillStatus("")
	}
	return o.Status
}

func (o *PlatformSkill) GetOrigin() PlatformSkillOrigin {
	if o == nil {
		return PlatformSkillOrigin("")
	}
	return o.Origin
}

func (o *PlatformSkill) GetSourceProvenance() *PlatformSkillSourceProvenance {
	if o == nil {
		return nil
	}
	return o.SourceProvenance
}

func (o *PlatformSkill) GetOwner() PlatformPersonReference {
	if o == nil {
		return PlatformPersonReference{}
	}
	return o.Owner
}

func (o *PlatformSkill) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *PlatformSkill) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
