// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 156b85c929fd

package components

// PlatformPersonalRequestCreate - New request for the authenticated canonical user in the server's current UTC month.
type PlatformPersonalRequestCreate struct {
	// Explicit spend client whose limit the request concerns.
	ClientID string `json:"client_id"`
	// Optional explanation of why the increase is needed.
	BusinessJustification *string `json:"business_justification,omitempty"`
}

func (o *PlatformPersonalRequestCreate) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *PlatformPersonalRequestCreate) GetBusinessJustification() *string {
	if o == nil {
		return nil
	}
	return o.BusinessJustification
}
