// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 312434003494

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

type PlatformSkillSourceProvenance struct {
	// URL of the external source the skill was imported from.
	SourceURL *string `json:"source_url,omitempty"`
	// Source commit SHA for the imported skill.
	CommitSha *string `json:"commit_sha,omitempty"`
	// Time the skill was imported.
	ImportedAt *time.Time `json:"imported_at,omitempty"`
	// Time the skill was last synced from its source.
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
	// Current external-source sync status.
	SyncStatus *PlatformSkillSyncStatus `json:"sync_status,omitempty"`
	// Human-readable sync failure reason, present only when sync_status is SYNC_FAILED.
	SyncError *string `json:"sync_error,omitempty"`
}

func (p PlatformSkillSourceProvenance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSkillSourceProvenance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *PlatformSkillSourceProvenance) GetSourceURL() *string {
	if o == nil {
		return nil
	}
	return o.SourceURL
}

func (o *PlatformSkillSourceProvenance) GetCommitSha() *string {
	if o == nil {
		return nil
	}
	return o.CommitSha
}

func (o *PlatformSkillSourceProvenance) GetImportedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ImportedAt
}

func (o *PlatformSkillSourceProvenance) GetLastSyncedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastSyncedAt
}

func (o *PlatformSkillSourceProvenance) GetSyncStatus() *PlatformSkillSyncStatus {
	if o == nil {
		return nil
	}
	return o.SyncStatus
}

func (o *PlatformSkillSourceProvenance) GetSyncError() *string {
	if o == nil {
		return nil
	}
	return o.SyncError
}
