// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4b01d54383cf

package components

// PlatformPersonReference - A lightweight reference to a person, used where a payload merely points at someone.
type PlatformPersonReference struct {
	// Opaque Glean person ID.
	ID *string `json:"id,omitempty"`
	// Display name.
	Name string `json:"name"`
}

func (o *PlatformPersonReference) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PlatformPersonReference) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
