// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3073b8cf092d

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type PlatformChatInputMessageRole string

const (
	PlatformChatInputMessageRoleUser      PlatformChatInputMessageRole = "user"
	PlatformChatInputMessageRoleAssistant PlatformChatInputMessageRole = "assistant"
)

func (e PlatformChatInputMessageRole) ToPointer() *PlatformChatInputMessageRole {
	return &e
}
func (e *PlatformChatInputMessageRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user":
		fallthrough
	case "assistant":
		*e = PlatformChatInputMessageRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlatformChatInputMessageRole: %v", v)
	}
}

type PlatformChatInputMessage struct {
	Role    PlatformChatInputMessageRole `json:"role"`
	Content string                       `json:"content"`
}

func (p PlatformChatInputMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformChatInputMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"role", "content"}); err != nil {
		return err
	}
	return nil
}

func (o *PlatformChatInputMessage) GetRole() PlatformChatInputMessageRole {
	if o == nil {
		return PlatformChatInputMessageRole("")
	}
	return o.Role
}

func (o *PlatformChatInputMessage) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}
