// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8f56121059d0

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
	"time"
)

type Object string

const (
	ObjectResponse Object = "RESPONSE"
)

func (e Object) ToPointer() *Object {
	return &e
}
func (e *Object) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "RESPONSE":
		*e = Object(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Object: %v", v)
	}
}

type PlatformChatCompletedResponseStatus string

const (
	PlatformChatCompletedResponseStatusCompleted PlatformChatCompletedResponseStatus = "COMPLETED"
)

func (e PlatformChatCompletedResponseStatus) ToPointer() *PlatformChatCompletedResponseStatus {
	return &e
}
func (e *PlatformChatCompletedResponseStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "COMPLETED":
		*e = PlatformChatCompletedResponseStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlatformChatCompletedResponseStatus: %v", v)
	}
}

type PlatformChatCompletedResponse struct {
	// Platform-owned, non-persisted response envelope identifier in `resp_<uuid>` form. The same identifier is used for every event in one streamed response.
	//
	ID     string `json:"id"`
	Object Object `json:"object"`
	// RFC 3339 UTC timestamp when the response was created.
	CreatedAt time.Time                           `json:"created_at"`
	Status    PlatformChatCompletedResponseStatus `json:"status"`
	Output    []PlatformChatOutputMessage         `json:"output"`
	Store     bool                                `json:"store"`
	// Present when the interaction was persisted.
	ConversationID optionalnullable.OptionalNullable[string] `json:"conversation_id,omitempty"`
	RequestID      string                                    `json:"request_id"`
}

func (p PlatformChatCompletedResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformChatCompletedResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"id", "object", "created_at", "status", "output", "store", "request_id"}); err != nil {
		return err
	}
	return nil
}

func (o *PlatformChatCompletedResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PlatformChatCompletedResponse) GetObject() Object {
	if o == nil {
		return Object("")
	}
	return o.Object
}

func (o *PlatformChatCompletedResponse) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *PlatformChatCompletedResponse) GetStatus() PlatformChatCompletedResponseStatus {
	if o == nil {
		return PlatformChatCompletedResponseStatus("")
	}
	return o.Status
}

func (o *PlatformChatCompletedResponse) GetOutput() []PlatformChatOutputMessage {
	if o == nil {
		return []PlatformChatOutputMessage{}
	}
	return o.Output
}

func (o *PlatformChatCompletedResponse) GetStore() bool {
	if o == nil {
		return false
	}
	return o.Store
}

func (o *PlatformChatCompletedResponse) GetConversationID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ConversationID
}

func (o *PlatformChatCompletedResponse) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}
