// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: be8e445dff34

package components

import (
	"encoding/json"
	"fmt"
)

// PlatformUserInclude - An optional field group to add to each user.
type PlatformUserInclude string

const (
	PlatformUserIncludeDatasourceProfiles PlatformUserInclude = "DATASOURCE_PROFILES"
)

func (e PlatformUserInclude) ToPointer() *PlatformUserInclude {
	return &e
}
func (e *PlatformUserInclude) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DATASOURCE_PROFILES":
		*e = PlatformUserInclude(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PlatformUserInclude: %v", v)
	}
}
