// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 62ce1621a216

package components

import (
	"encoding/json"
	"fmt"
)

// ServerToolRequestRequestType - The type of request made to the user.
type ServerToolRequestRequestType string

const (
	ServerToolRequestRequestTypeExecution                ServerToolRequestRequestType = "EXECUTION"
	ServerToolRequestRequestTypeAuthenticationSuggestion ServerToolRequestRequestType = "AUTHENTICATION_SUGGESTION"
	ServerToolRequestRequestTypeVoteSuggestion           ServerToolRequestRequestType = "VOTE_SUGGESTION"
	ServerToolRequestRequestTypeSandboxEgress            ServerToolRequestRequestType = "SANDBOX_EGRESS"
)

func (e ServerToolRequestRequestType) ToPointer() *ServerToolRequestRequestType {
	return &e
}
func (e *ServerToolRequestRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EXECUTION":
		fallthrough
	case "AUTHENTICATION_SUGGESTION":
		fallthrough
	case "VOTE_SUGGESTION":
		fallthrough
	case "SANDBOX_EGRESS":
		*e = ServerToolRequestRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ServerToolRequestRequestType: %v", v)
	}
}

type ServerToolRequest struct {
	// The type of request made to the user.
	RequestType ServerToolRequestRequestType `json:"requestType"`
	// Unique identifier for this request.
	RequestID string `json:"requestId"`
	// Human-readable display name for the tool.
	ToolDisplayName *string `json:"toolDisplayName,omitempty"`
	// Unique identifier of the tool server. Use with GET /tool-servers/{serverId}/auth
	// to resolve display information and authentication status.
	//
	ServerID *string `json:"serverId,omitempty"`
	// Custom call-to-action (CTA) verb for the approval button (e.g., "Create", "Update", "Send").
	ToolCta *string `json:"toolCta,omitempty"`
	// Preview information for an action being executed.
	ActionPreview *ActionPreview `json:"actionPreview,omitempty"`
}

func (o *ServerToolRequest) GetRequestType() ServerToolRequestRequestType {
	if o == nil {
		return ServerToolRequestRequestType("")
	}
	return o.RequestType
}

func (o *ServerToolRequest) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

func (o *ServerToolRequest) GetToolDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.ToolDisplayName
}

func (o *ServerToolRequest) GetServerID() *string {
	if o == nil {
		return nil
	}
	return o.ServerID
}

func (o *ServerToolRequest) GetToolCta() *string {
	if o == nil {
		return nil
	}
	return o.ToolCta
}

func (o *ServerToolRequest) GetActionPreview() *ActionPreview {
	if o == nil {
		return nil
	}
	return o.ActionPreview
}
