// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cf8b2fc0477f

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
)

// ServerToolResponseRequestType - The type of request made to the user.
type ServerToolResponseRequestType string

const (
	ServerToolResponseRequestTypeExecution                ServerToolResponseRequestType = "EXECUTION"
	ServerToolResponseRequestTypeAuthenticationSuggestion ServerToolResponseRequestType = "AUTHENTICATION_SUGGESTION"
	ServerToolResponseRequestTypeVoteSuggestion           ServerToolResponseRequestType = "VOTE_SUGGESTION"
	ServerToolResponseRequestTypeSandboxEgress            ServerToolResponseRequestType = "SANDBOX_EGRESS"
)

func (e ServerToolResponseRequestType) ToPointer() *ServerToolResponseRequestType {
	return &e
}
func (e *ServerToolResponseRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EXECUTION":
		fallthrough
	case "AUTHENTICATION_SUGGESTION":
		fallthrough
	case "VOTE_SUGGESTION":
		fallthrough
	case "SANDBOX_EGRESS":
		*e = ServerToolResponseRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ServerToolResponseRequestType: %v", v)
	}
}

// GrantScope - Scope of the approval grant. Only applicable when isGranted is true and requestType is EXECUTION.
type GrantScope string

const (
	GrantScopeCurrentRequest GrantScope = "CURRENT_REQUEST"
	GrantScopeCurrentSession GrantScope = "CURRENT_SESSION"
	GrantScopeAlways         GrantScope = "ALWAYS"
)

func (e GrantScope) ToPointer() *GrantScope {
	return &e
}
func (e *GrantScope) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CURRENT_REQUEST":
		fallthrough
	case "CURRENT_SESSION":
		fallthrough
	case "ALWAYS":
		*e = GrantScope(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GrantScope: %v", v)
	}
}

// ServerToolResponse - Response to a server tool request. The applicable fields depend on requestType:
//
// For EXECUTION requests:
// - isGranted: whether tool execution is approved
// - reason: optional explanation
//
// For AUTHENTICATION_SUGGESTION requests:
// - isGranted: whether auth completed successfully (true=connected, false=skipped)
// - authContext: contains serverId or actionPackId for identifying the authenticated entity
// - reason: optional explanation for skip
//
// For VOTE_SUGGESTION requests:
// - voted: whether the user voted for this tool
//
// For SANDBOX_EGRESS requests:
// - isGranted: whether the sandbox egress call is approved
type ServerToolResponse struct {
	// The type of request made to the user.
	RequestType ServerToolResponseRequestType `json:"requestType"`
	// Unique identifier for this request.
	RequestID string `json:"requestId"`
	// Whether tool request is granted (indicates approval for execution, or completion for auth).
	IsGranted *bool `json:"isGranted,omitempty"`
	// Scope of the approval grant. Only applicable when isGranted is true and requestType is EXECUTION.
	//
	GrantScope *GrantScope `default:"CURRENT_REQUEST" json:"grantScope"`
	// Context for authentication responses, containing identifiers for the entity being authenticated.
	//
	AuthContext *AuthContext `json:"authContext,omitempty"`
}

func (s ServerToolResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ServerToolResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"requestType", "requestId"}); err != nil {
		return err
	}
	return nil
}

func (o *ServerToolResponse) GetRequestType() ServerToolResponseRequestType {
	if o == nil {
		return ServerToolResponseRequestType("")
	}
	return o.RequestType
}

func (o *ServerToolResponse) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

func (o *ServerToolResponse) GetIsGranted() *bool {
	if o == nil {
		return nil
	}
	return o.IsGranted
}

func (o *ServerToolResponse) GetGrantScope() *GrantScope {
	if o == nil {
		return nil
	}
	return o.GrantScope
}

func (o *ServerToolResponse) GetAuthContext() *AuthContext {
	if o == nil {
		return nil
	}
	return o.AuthContext
}
