// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2cf5a5147c6b

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
	"time"
)

// ViewerInfoRole - DEPRECATED - use permissions instead. Viewer's role on the specific document.
//
// Deprecated: Deprecated on 2026-02-05, removal scheduled for 2026-10-15: Use permissions instead.
type ViewerInfoRole string

const (
	ViewerInfoRoleAnswerModerator ViewerInfoRole = "ANSWER_MODERATOR"
	ViewerInfoRoleOwner           ViewerInfoRole = "OWNER"
	ViewerInfoRoleViewer          ViewerInfoRole = "VIEWER"
)

func (e ViewerInfoRole) ToPointer() *ViewerInfoRole {
	return &e
}
func (e *ViewerInfoRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ANSWER_MODERATOR":
		fallthrough
	case "OWNER":
		fallthrough
	case "VIEWER":
		*e = ViewerInfoRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ViewerInfoRole: %v", v)
	}
}

type ViewerInfo struct {
	// DEPRECATED - use permissions instead. Viewer's role on the specific document.
	//
	// Deprecated: Deprecated on 2026-02-05, removal scheduled for 2026-10-15: Use permissions instead.
	Role           *ViewerInfoRole `json:"role,omitempty"`
	LastViewedTime *time.Time      `json:"lastViewedTime,omitempty"`
}

func (v ViewerInfo) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *ViewerInfo) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ViewerInfo) GetRole() *ViewerInfoRole {
	if o == nil {
		return nil
	}
	return o.Role
}

func (o *ViewerInfo) GetLastViewedTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.LastViewedTime
}
