/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 225adf458c37
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Preview information for an action being executed.
 */
export type ActionPreview = {
  /**
   * Markdown preview describing what the action will do.
   */
  markdown?: string | undefined;
  /**
   * Short summary of what this specific tool invocation will do.
   */
  description?: string | undefined;
};

/** @internal */
export const ActionPreview$inboundSchema: z.ZodType<
  ActionPreview,
  z.ZodTypeDef,
  unknown
> = z.object({
  markdown: z.string().optional(),
  description: z.string().optional(),
});
/** @internal */
export type ActionPreview$Outbound = {
  markdown?: string | undefined;
  description?: string | undefined;
};

/** @internal */
export const ActionPreview$outboundSchema: z.ZodType<
  ActionPreview$Outbound,
  z.ZodTypeDef,
  ActionPreview
> = z.object({
  markdown: z.string().optional(),
  description: z.string().optional(),
});

export function actionPreviewToJSON(actionPreview: ActionPreview): string {
  return JSON.stringify(ActionPreview$outboundSchema.parse(actionPreview));
}
export function actionPreviewFromJSON(
  jsonString: string,
): SafeParseResult<ActionPreview, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionPreview$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionPreview' from JSON`,
  );
}
