/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f866ea22e796
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ActionPackAuthStatus,
  ActionPackAuthStatus$inboundSchema,
} from "./actionpackauthstatus.js";

export type ActionPackAuthStatusResponse = {
  actionPack: ActionPackAuthStatus;
};

/** @internal */
export const ActionPackAuthStatusResponse$inboundSchema: z.ZodType<
  ActionPackAuthStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  actionPack: ActionPackAuthStatus$inboundSchema,
});

export function actionPackAuthStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActionPackAuthStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionPackAuthStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionPackAuthStatusResponse' from JSON`,
  );
}
