/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Current status of the file.
 */
export const ChatFileStatus = {
  Processing: "PROCESSING",
  Processed: "PROCESSED",
  Failed: "FAILED",
  Deleted: "DELETED",
} as const;
/**
 * Current status of the file.
 */
export type ChatFileStatus = ClosedEnum<typeof ChatFileStatus>;

/** @internal */
export const ChatFileStatus$inboundSchema: z.ZodNativeEnum<
  typeof ChatFileStatus
> = z.nativeEnum(ChatFileStatus);
/** @internal */
export const ChatFileStatus$outboundSchema: z.ZodNativeEnum<
  typeof ChatFileStatus
> = ChatFileStatus$inboundSchema;
