/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Describes the request body of the /checkdocumentaccess API call
 */
export type CheckDocumentAccessRequest = {
  /**
   * Datasource of document to check access for.
   */
  datasource: string;
  /**
   * Object type of document to check access for.
   */
  objectType: string;
  /**
   * Glean Document ID to check access for.
   */
  docId: string;
  /**
   * Email of user to check access for.
   */
  userEmail: string;
};

/** @internal */
export type CheckDocumentAccessRequest$Outbound = {
  datasource: string;
  objectType: string;
  docId: string;
  userEmail: string;
};

/** @internal */
export const CheckDocumentAccessRequest$outboundSchema: z.ZodType<
  CheckDocumentAccessRequest$Outbound,
  z.ZodTypeDef,
  CheckDocumentAccessRequest
> = z.object({
  datasource: z.string(),
  objectType: z.string(),
  docId: z.string(),
  userEmail: z.string(),
});

export function checkDocumentAccessRequestToJSON(
  checkDocumentAccessRequest: CheckDocumentAccessRequest,
): string {
  return JSON.stringify(
    CheckDocumentAccessRequest$outboundSchema.parse(checkDocumentAccessRequest),
  );
}
