/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 951dfb6561cd
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Categories a Collection can be pinned to.
 */
export const CollectionPinnableCategories = {
  CompanyResource: "COMPANY_RESOURCE",
  DepartmentResource: "DEPARTMENT_RESOURCE",
  TeamResource: "TEAM_RESOURCE",
} as const;
/**
 * Categories a Collection can be pinned to.
 */
export type CollectionPinnableCategories = OpenEnum<
  typeof CollectionPinnableCategories
>;

/** @internal */
export const CollectionPinnableCategories$inboundSchema: z.ZodType<
  CollectionPinnableCategories,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CollectionPinnableCategories);
/** @internal */
export const CollectionPinnableCategories$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  CollectionPinnableCategories
> = openEnums.outboundSchema(CollectionPinnableCategories);
