/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 44f460feae77
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * What targets can a Collection be pinned to.
 */
export const CollectionPinnableTargets = {
  ResourceCard: "RESOURCE_CARD",
  TeamProfilePage: "TEAM_PROFILE_PAGE",
} as const;
/**
 * What targets can a Collection be pinned to.
 */
export type CollectionPinnableTargets = OpenEnum<
  typeof CollectionPinnableTargets
>;

/** @internal */
export const CollectionPinnableTargets$inboundSchema: z.ZodType<
  CollectionPinnableTargets,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CollectionPinnableTargets);
/** @internal */
export const CollectionPinnableTargets$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  CollectionPinnableTargets
> = openEnums.outboundSchema(CollectionPinnableTargets);
