/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { DlpReport, DlpReport$inboundSchema } from "./dlpreport.js";

export type CreateDlpReportResponse = {
  /**
   * Full policy information that will be used for scans.
   */
  report?: DlpReport | undefined;
};

/** @internal */
export const CreateDlpReportResponse$inboundSchema: z.ZodType<
  CreateDlpReportResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  report: DlpReport$inboundSchema.optional(),
});

export function createDlpReportResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateDlpReportResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateDlpReportResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateDlpReportResponse' from JSON`,
  );
}
