/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CurrentActiveUsers = {
  /**
   * Number of current Monthly Active Users, in the specified departments.
   */
  monthlyActiveUsers?: number | undefined;
  /**
   * Number of current Weekly Active Users, in the specified departments.
   */
  weeklyActiveUsers?: number | undefined;
};

/** @internal */
export const CurrentActiveUsers$inboundSchema: z.ZodType<
  CurrentActiveUsers,
  z.ZodTypeDef,
  unknown
> = z.object({
  monthlyActiveUsers: z.number().int().optional(),
  weeklyActiveUsers: z.number().int().optional(),
});

export function currentActiveUsersFromJSON(
  jsonString: string,
): SafeParseResult<CurrentActiveUsers, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CurrentActiveUsers$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CurrentActiveUsers' from JSON`,
  );
}
