/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8d6c96706d55
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomDataValue,
  CustomDataValue$inboundSchema,
  CustomDataValue$Outbound,
  CustomDataValue$outboundSchema,
} from "./customdatavalue.js";

export type CustomerMetadata = {
  /**
   * The user visible id of the salesforce customer account.
   */
  datasourceId?: string | undefined;
  /**
   * Custom fields specific to individual datasources
   */
  customData?: { [k: string]: CustomDataValue } | undefined;
};

/** @internal */
export const CustomerMetadata$inboundSchema: z.ZodType<
  CustomerMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  datasourceId: z.string().optional(),
  customData: z.record(CustomDataValue$inboundSchema).optional(),
});
/** @internal */
export type CustomerMetadata$Outbound = {
  datasourceId?: string | undefined;
  customData?: { [k: string]: CustomDataValue$Outbound } | undefined;
};

/** @internal */
export const CustomerMetadata$outboundSchema: z.ZodType<
  CustomerMetadata$Outbound,
  z.ZodTypeDef,
  CustomerMetadata
> = z.object({
  datasourceId: z.string().optional(),
  customData: z.record(CustomDataValue$outboundSchema).optional(),
});

export function customerMetadataToJSON(
  customerMetadata: CustomerMetadata,
): string {
  return JSON.stringify(
    CustomerMetadata$outboundSchema.parse(customerMetadata),
  );
}
export function customerMetadataFromJSON(
  jsonString: string,
): SafeParseResult<CustomerMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerMetadata' from JSON`,
  );
}
