/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: ae5cc5be791d
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Lifecycle state of the credentials installed for a datasource instance. Mirrors the internal admin Status enum so the handler can surface the same health signals already tracked today. EXPIRING_SOON is represented as VALID_WITH_WARNINGS (with detail in `message`); EXPIRED is surfaced as INVALID plus a non-null `expiresAt` in the past.
 *
 * @remarks
 */
export const DatasourceCredentialStatus = {
  Valid: "VALID",
  ValidWithWarnings: "VALID_WITH_WARNINGS",
  Validating: "VALIDATING",
  Invalid: "INVALID",
  Missing: "MISSING",
} as const;
/**
 * Lifecycle state of the credentials installed for a datasource instance. Mirrors the internal admin Status enum so the handler can surface the same health signals already tracked today. EXPIRING_SOON is represented as VALID_WITH_WARNINGS (with detail in `message`); EXPIRED is surfaced as INVALID plus a non-null `expiresAt` in the past.
 *
 * @remarks
 */
export type DatasourceCredentialStatus = OpenEnum<
  typeof DatasourceCredentialStatus
>;

/** @internal */
export const DatasourceCredentialStatus$inboundSchema: z.ZodType<
  DatasourceCredentialStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(DatasourceCredentialStatus);
