/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2880c56952b3
 */

import * as z from "zod/v3";
import {
  DebugDocumentRequest,
  DebugDocumentRequest$Outbound,
  DebugDocumentRequest$outboundSchema,
} from "./debugdocumentrequest.js";

/**
 * Describes the request body of the /debug/{datasource}/documents API call.
 */
export type DebugDocumentsRequest = {
  /**
   * Documents to fetch debug information for
   */
  debugDocuments: Array<DebugDocumentRequest>;
};

/** @internal */
export type DebugDocumentsRequest$Outbound = {
  debugDocuments: Array<DebugDocumentRequest$Outbound>;
};

/** @internal */
export const DebugDocumentsRequest$outboundSchema: z.ZodType<
  DebugDocumentsRequest$Outbound,
  z.ZodTypeDef,
  DebugDocumentsRequest
> = z.object({
  debugDocuments: z.array(DebugDocumentRequest$outboundSchema),
});

export function debugDocumentsRequestToJSON(
  debugDocumentsRequest: DebugDocumentsRequest,
): string {
  return JSON.stringify(
    DebugDocumentsRequest$outboundSchema.parse(debugDocumentsRequest),
  );
}
