/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteAnnouncementRequest = {
  /**
   * The opaque id of the announcement to be deleted.
   */
  id: number;
};

/** @internal */
export type DeleteAnnouncementRequest$Outbound = {
  id: number;
};

/** @internal */
export const DeleteAnnouncementRequest$outboundSchema: z.ZodType<
  DeleteAnnouncementRequest$Outbound,
  z.ZodTypeDef,
  DeleteAnnouncementRequest
> = z.object({
  id: z.number().int(),
});

export function deleteAnnouncementRequestToJSON(
  deleteAnnouncementRequest: DeleteAnnouncementRequest,
): string {
  return JSON.stringify(
    DeleteAnnouncementRequest$outboundSchema.parse(deleteAnnouncementRequest),
  );
}
