/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f0dd3f4154df
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import {
  DlpFindingFilter,
  DlpFindingFilter$Outbound,
  DlpFindingFilter$outboundSchema,
} from "./dlpfindingfilter.js";
import {
  DlpIssueFilter,
  DlpIssueFilter$Outbound,
  DlpIssueFilter$outboundSchema,
} from "./dlpissuefilter.js";

/**
 * The type of export to perform
 */
export const DlpExportFindingsRequestExportType = {
  Findings: "FINDINGS",
  Documents: "DOCUMENTS",
  Issues: "ISSUES",
} as const;
/**
 * The type of export to perform
 */
export type DlpExportFindingsRequestExportType = ClosedEnum<
  typeof DlpExportFindingsRequestExportType
>;

/**
 * Controls which fields to include in the export
 */
export const FieldScope = {
  All: "ALL",
  ExcludeSensitive: "EXCLUDE_SENSITIVE",
  Custom: "CUSTOM",
} as const;
/**
 * Controls which fields to include in the export
 */
export type FieldScope = ClosedEnum<typeof FieldScope>;

export type DlpExportFindingsRequest = {
  /**
   * The type of export to perform
   */
  exportType?: DlpExportFindingsRequestExportType | undefined;
  filter?: DlpFindingFilter | undefined;
  /**
   * Filter for DLP issues. Includes document-level filters and issue-specific filters.
   */
  issueFilter?: DlpIssueFilter | undefined;
  /**
   * The name of the file to export the findings to
   */
  fileName?: string | undefined;
  /**
   * Controls which fields to include in the export
   */
  fieldScope?: FieldScope | undefined;
  /**
   * List of field names to exclude from the export
   */
  fieldsToExclude?: Array<string> | undefined;
};

/** @internal */
export const DlpExportFindingsRequestExportType$outboundSchema: z.ZodNativeEnum<
  typeof DlpExportFindingsRequestExportType
> = z.nativeEnum(DlpExportFindingsRequestExportType);

/** @internal */
export const FieldScope$outboundSchema: z.ZodNativeEnum<typeof FieldScope> = z
  .nativeEnum(FieldScope);

/** @internal */
export type DlpExportFindingsRequest$Outbound = {
  exportType?: string | undefined;
  filter?: DlpFindingFilter$Outbound | undefined;
  issueFilter?: DlpIssueFilter$Outbound | undefined;
  fileName?: string | undefined;
  fieldScope?: string | undefined;
  fieldsToExclude?: Array<string> | undefined;
};

/** @internal */
export const DlpExportFindingsRequest$outboundSchema: z.ZodType<
  DlpExportFindingsRequest$Outbound,
  z.ZodTypeDef,
  DlpExportFindingsRequest
> = z.object({
  exportType: DlpExportFindingsRequestExportType$outboundSchema.optional(),
  filter: DlpFindingFilter$outboundSchema.optional(),
  issueFilter: DlpIssueFilter$outboundSchema.optional(),
  fileName: z.string().optional(),
  fieldScope: FieldScope$outboundSchema.optional(),
  fieldsToExclude: z.array(z.string()).optional(),
});

export function dlpExportFindingsRequestToJSON(
  dlpExportFindingsRequest: DlpExportFindingsRequest,
): string {
  return JSON.stringify(
    DlpExportFindingsRequest$outboundSchema.parse(dlpExportFindingsRequest),
  );
}
