/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bd444ff86b3c
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const DlpSimpleResult = {
  Success: "SUCCESS",
  Failure: "FAILURE",
} as const;
export type DlpSimpleResult = OpenEnum<typeof DlpSimpleResult>;

/** @internal */
export const DlpSimpleResult$inboundSchema: z.ZodType<
  DlpSimpleResult,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(DlpSimpleResult);
