/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 544961797246
 */

import * as z from "zod/v3";

export type EditWorkflowRequest = {
  /**
   * The name of the workflow.
   */
  name?: string | undefined;
  /**
   * The workflow ID we want to update.
   */
  id?: string | undefined;
};

/** @internal */
export type EditWorkflowRequest$Outbound = {
  name?: string | undefined;
  id?: string | undefined;
};

/** @internal */
export const EditWorkflowRequest$outboundSchema: z.ZodType<
  EditWorkflowRequest$Outbound,
  z.ZodTypeDef,
  EditWorkflowRequest
> = z.object({
  name: z.string().optional(),
  id: z.string().optional(),
});

export function editWorkflowRequestToJSON(
  editWorkflowRequest: EditWorkflowRequest,
): string {
  return JSON.stringify(
    EditWorkflowRequest$outboundSchema.parse(editWorkflowRequest),
  );
}
