/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7a93a2fd6690
 */

import * as z from "zod/v3";

/**
 * Describes a relationship edge between a source and destination entity
 */
export type EntityRelationship = {
  /**
   * The title or type of relationship. Currently an enum of `CHIEF_OF_STAFF`, `EXECUTIVE_ASSISTANT`
   */
  name: string;
  /**
   * Email of the person with whom the relationship exists. Per the example above, either `B` or `C`'s email depending on the relationship.
   */
  email: string;
};

/** @internal */
export type EntityRelationship$Outbound = {
  name: string;
  email: string;
};

/** @internal */
export const EntityRelationship$outboundSchema: z.ZodType<
  EntityRelationship$Outbound,
  z.ZodTypeDef,
  EntityRelationship
> = z.object({
  name: z.string(),
  email: z.string(),
});

export function entityRelationshipToJSON(
  entityRelationship: EntityRelationship,
): string {
  return JSON.stringify(
    EntityRelationship$outboundSchema.parse(entityRelationship),
  );
}
