/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetChatApplicationResponse = {
  application?: any | undefined;
};

/** @internal */
export const GetChatApplicationResponse$inboundSchema: z.ZodType<
  GetChatApplicationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  application: z.any().optional(),
});

export function getChatApplicationResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetChatApplicationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetChatApplicationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetChatApplicationResponse' from JSON`,
  );
}
