/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7f7d4b668bb0
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { DlpReport, DlpReport$inboundSchema } from "./dlpreport.js";

export type GetDlpReportResponse = {
  /**
   * Full policy information that will be used for scans.
   */
  report?: DlpReport | undefined;
};

/** @internal */
export const GetDlpReportResponse$inboundSchema: z.ZodType<
  GetDlpReportResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  report: DlpReport$inboundSchema.optional(),
});

export function getDlpReportResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDlpReportResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDlpReportResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDlpReportResponse' from JSON`,
  );
}
