/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7d2648b471e1
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import {
  DocumentSpecUnion,
  DocumentSpecUnion$Outbound,
  DocumentSpecUnion$outboundSchema,
} from "./documentspecunion.js";

export const GetDocumentsRequestIncludeField = {
  LastViewedAt: "LAST_VIEWED_AT",
  VisitorsCount: "VISITORS_COUNT",
  RecentShares: "RECENT_SHARES",
  DocumentContent: "DOCUMENT_CONTENT",
  CustomMetadata: "CUSTOM_METADATA",
} as const;
export type GetDocumentsRequestIncludeField = ClosedEnum<
  typeof GetDocumentsRequestIncludeField
>;

export type GetDocumentsRequest = {
  /**
   * The specification for the documents to be retrieved.
   */
  documentSpecs: Array<DocumentSpecUnion>;
  /**
   * List of Document fields to return (that aren't returned by default)
   */
  includeFields?: Array<GetDocumentsRequestIncludeField> | undefined;
};

/** @internal */
export const GetDocumentsRequestIncludeField$outboundSchema: z.ZodNativeEnum<
  typeof GetDocumentsRequestIncludeField
> = z.nativeEnum(GetDocumentsRequestIncludeField);

/** @internal */
export type GetDocumentsRequest$Outbound = {
  documentSpecs: Array<DocumentSpecUnion$Outbound>;
  includeFields?: Array<string> | undefined;
};

/** @internal */
export const GetDocumentsRequest$outboundSchema: z.ZodType<
  GetDocumentsRequest$Outbound,
  z.ZodTypeDef,
  GetDocumentsRequest
> = z.object({
  documentSpecs: z.array(DocumentSpecUnion$outboundSchema),
  includeFields: z.array(GetDocumentsRequestIncludeField$outboundSchema)
    .optional(),
});

export function getDocumentsRequestToJSON(
  getDocumentsRequest: GetDocumentsRequest,
): string {
  return JSON.stringify(
    GetDocumentsRequest$outboundSchema.parse(getDocumentsRequest),
  );
}
