/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Describes the request body of the /betausers API call
 */
export type GreenlistUsersRequest = {
  /**
   * Datasource which needs to be made visible to users specified in the `emails` field.
   */
  datasource: string;
  /**
   * The emails of the beta users
   */
  emails: Array<string>;
};

/** @internal */
export type GreenlistUsersRequest$Outbound = {
  datasource: string;
  emails: Array<string>;
};

/** @internal */
export const GreenlistUsersRequest$outboundSchema: z.ZodType<
  GreenlistUsersRequest$Outbound,
  z.ZodTypeDef,
  GreenlistUsersRequest
> = z.object({
  datasource: z.string(),
  emails: z.array(z.string()),
});

export function greenlistUsersRequestToJSON(
  greenlistUsersRequest: GreenlistUsersRequest,
): string {
  return JSON.stringify(
    GreenlistUsersRequest$outboundSchema.parse(greenlistUsersRequest),
  );
}
