/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d131f4a57b51
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ImportAgentStatus,
  ImportAgentStatus$inboundSchema,
} from "./importagentstatus.js";
import {
  WorkflowResult,
  WorkflowResult$inboundSchema,
} from "./workflowresult.js";

export type ImportAgentResponse = {
  workflowResult?: WorkflowResult | undefined;
  /**
   * Outcome of the import for the target agent.
   */
  status?: ImportAgentStatus | undefined;
};

/** @internal */
export const ImportAgentResponse$inboundSchema: z.ZodType<
  ImportAgentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  workflowResult: WorkflowResult$inboundSchema.optional(),
  status: ImportAgentStatus$inboundSchema.optional(),
});

export function importAgentResponseFromJSON(
  jsonString: string,
): SafeParseResult<ImportAgentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImportAgentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImportAgentResponse' from JSON`,
  );
}
