/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 58982746383b
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Whether the imported version is staged (saved without updating the live version) or published directly to the live version.
 *
 * @remarks
 */
export const ImportAgentSyncMode = {
  Staged: "STAGED",
  Published: "PUBLISHED",
} as const;
/**
 * Whether the imported version is staged (saved without updating the live version) or published directly to the live version.
 *
 * @remarks
 */
export type ImportAgentSyncMode = ClosedEnum<typeof ImportAgentSyncMode>;

/** @internal */
export const ImportAgentSyncMode$outboundSchema: z.ZodNativeEnum<
  typeof ImportAgentSyncMode
> = z.nativeEnum(ImportAgentSyncMode);
