/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 85de0a4396af
 */

import * as z from "zod/v3";
import { blobLikeSchema } from "../../types/blobs.js";
import {
  ImportAgentSyncMode,
  ImportAgentSyncMode$outboundSchema,
} from "./importagentsyncmode.js";

export type Bundle = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type ImportAgentRequest = {
  /**
   * Zip of the agent folder (spec.yaml, instructions.md, skills/, subagents/) with symlinks dereferenced.
   *
   * @remarks
   */
  bundle: Bundle | Blob;
  /**
   * Optional Git commit SHA to associate with this import.
   */
  gitCommitSha?: string | undefined;
  /**
   * Optional VCS commit author ID to associate with this import.
   */
  gitAuthorId?: string | undefined;
  /**
   * Optional commit message for the imported version.
   */
  commitMessage?: string | undefined;
  /**
   * Whether the imported version is staged (saved without updating the live version) or published directly to the live version.
   *
   * @remarks
   */
  syncMode?: ImportAgentSyncMode | undefined;
  /**
   * Deprecated. Draft mutation semantics are not supported for transient previews. Use transient and parentWorkflowId instead.
   *
   * @remarks
   */
  isDraft?: boolean | undefined;
};

/** @internal */
export type Bundle$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const Bundle$outboundSchema: z.ZodType<
  Bundle$Outbound,
  z.ZodTypeDef,
  Bundle
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
});

export function bundleToJSON(bundle: Bundle): string {
  return JSON.stringify(Bundle$outboundSchema.parse(bundle));
}

/** @internal */
export type ImportAgentRequest$Outbound = {
  bundle: Bundle$Outbound | Blob;
  gitCommitSha?: string | undefined;
  gitAuthorId?: string | undefined;
  commitMessage?: string | undefined;
  syncMode?: string | undefined;
  isDraft?: boolean | undefined;
};

/** @internal */
export const ImportAgentRequest$outboundSchema: z.ZodType<
  ImportAgentRequest$Outbound,
  z.ZodTypeDef,
  ImportAgentRequest
> = z.object({
  bundle: z.lazy(() => Bundle$outboundSchema).or(blobLikeSchema),
  gitCommitSha: z.string().optional(),
  gitAuthorId: z.string().optional(),
  commitMessage: z.string().optional(),
  syncMode: ImportAgentSyncMode$outboundSchema.optional(),
  isDraft: z.boolean().optional(),
});

export function importAgentRequestToJSON(
  importAgentRequest: ImportAgentRequest,
): string {
  return JSON.stringify(
    ImportAgentRequest$outboundSchema.parse(importAgentRequest),
  );
}
