/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a5976c2680c1
 */

import * as z from "zod/v3";
import {
  EmployeeInfoDefinition,
  EmployeeInfoDefinition$Outbound,
  EmployeeInfoDefinition$outboundSchema,
} from "./employeeinfodefinition.js";

/**
 * Info about an employee and optional version for that info
 */
export type IndexEmployeeRequest = {
  /**
   * Describes employee info
   */
  employee: EmployeeInfoDefinition;
  /**
   * Version number for the employee object. If absent or 0 then no version checks are done
   */
  version?: number | undefined;
};

/** @internal */
export type IndexEmployeeRequest$Outbound = {
  employee: EmployeeInfoDefinition$Outbound;
  version?: number | undefined;
};

/** @internal */
export const IndexEmployeeRequest$outboundSchema: z.ZodType<
  IndexEmployeeRequest$Outbound,
  z.ZodTypeDef,
  IndexEmployeeRequest
> = z.object({
  employee: EmployeeInfoDefinition$outboundSchema,
  version: z.number().int().optional(),
});

export function indexEmployeeRequestToJSON(
  indexEmployeeRequest: IndexEmployeeRequest,
): string {
  return JSON.stringify(
    IndexEmployeeRequest$outboundSchema.parse(indexEmployeeRequest),
  );
}
