/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  AgentsInsightsV2Request,
  AgentsInsightsV2Request$Outbound,
  AgentsInsightsV2Request$outboundSchema,
} from "./agentsinsightsv2request.js";
import {
  InsightsAssistantRequest,
  InsightsAssistantRequest$Outbound,
  InsightsAssistantRequest$outboundSchema,
} from "./insightsassistantrequest.js";
import {
  InsightsOverviewRequest,
  InsightsOverviewRequest$Outbound,
  InsightsOverviewRequest$outboundSchema,
} from "./insightsoverviewrequest.js";

export type InsightsRequest = {
  overviewRequest?: InsightsOverviewRequest | undefined;
  assistantRequest?: InsightsAssistantRequest | undefined;
  agentsRequest?: AgentsInsightsV2Request | undefined;
  /**
   * If true, suppresses the generation of per-user Insights in the response. Default is false.
   */
  disablePerUserInsights?: boolean | undefined;
};

/** @internal */
export type InsightsRequest$Outbound = {
  overviewRequest?: InsightsOverviewRequest$Outbound | undefined;
  assistantRequest?: InsightsAssistantRequest$Outbound | undefined;
  agentsRequest?: AgentsInsightsV2Request$Outbound | undefined;
  disablePerUserInsights?: boolean | undefined;
};

/** @internal */
export const InsightsRequest$outboundSchema: z.ZodType<
  InsightsRequest$Outbound,
  z.ZodTypeDef,
  InsightsRequest
> = z.object({
  overviewRequest: InsightsOverviewRequest$outboundSchema.optional(),
  assistantRequest: InsightsAssistantRequest$outboundSchema.optional(),
  agentsRequest: AgentsInsightsV2Request$outboundSchema.optional(),
  disablePerUserInsights: z.boolean().optional(),
});

export function insightsRequestToJSON(
  insightsRequest: InsightsRequest,
): string {
  return JSON.stringify(InsightsRequest$outboundSchema.parse(insightsRequest));
}
