/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 34b336667db8
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Type of event
 */
export const LifeCycleEventEvent = {
  Uploaded: "UPLOADED",
  Indexed: "INDEXED",
  DeletionRequested: "DELETION_REQUESTED",
  Deleted: "DELETED",
} as const;
/**
 * Type of event
 */
export type LifeCycleEventEvent = OpenEnum<typeof LifeCycleEventEvent>;

export type LifeCycleEvent = {
  /**
   * Type of event
   */
  event?: LifeCycleEventEvent | undefined;
  /**
   * Timestamp of the event
   */
  timestamp?: string | undefined;
};

/** @internal */
export const LifeCycleEventEvent$inboundSchema: z.ZodType<
  LifeCycleEventEvent,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(LifeCycleEventEvent);

/** @internal */
export const LifeCycleEvent$inboundSchema: z.ZodType<
  LifeCycleEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  event: LifeCycleEventEvent$inboundSchema.optional(),
  timestamp: z.string().optional(),
});

export function lifeCycleEventFromJSON(
  jsonString: string,
): SafeParseResult<LifeCycleEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LifeCycleEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LifeCycleEvent' from JSON`,
  );
}
