/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChatMetadataResult,
  ChatMetadataResult$inboundSchema,
} from "./chatmetadataresult.js";

export type ListChatsResponse = {
  chatResults?: Array<ChatMetadataResult> | undefined;
};

/** @internal */
export const ListChatsResponse$inboundSchema: z.ZodType<
  ListChatsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  chatResults: z.array(ChatMetadataResult$inboundSchema).optional(),
});

export function listChatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListChatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListChatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListChatsResponse' from JSON`,
  );
}
