/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c0d51edaa588
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ExportInfo, ExportInfo$inboundSchema } from "./exportinfo.js";

export type ListDlpFindingsExportsResponse = {
  exports?: Array<ExportInfo> | undefined;
};

/** @internal */
export const ListDlpFindingsExportsResponse$inboundSchema: z.ZodType<
  ListDlpFindingsExportsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  exports: z.array(ExportInfo$inboundSchema).optional(),
});

export function listDlpFindingsExportsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDlpFindingsExportsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDlpFindingsExportsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDlpFindingsExportsResponse' from JSON`,
  );
}
