/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e4c173899120
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import { Period, Period$Outbound, Period$outboundSchema } from "./period.js";

/**
 * Type of breakdown to return.
 */
export const BreakdownType = {
  Users: "USERS",
  HostApplications: "HOST_APPLICATIONS",
  Tools: "TOOLS",
  Servers: "SERVERS",
} as const;
/**
 * Type of breakdown to return.
 */
export type BreakdownType = ClosedEnum<typeof BreakdownType>;

export type McpBreakdownInsightsRequest = {
  /**
   * Departments for which Insights are requested.
   */
  departments?: Array<string> | undefined;
  /**
   * Manager user IDs whose teams should be filtered for. Empty array means no filtering.
   */
  managerIds?: Array<string> | undefined;
  dayRange?: Period | undefined;
  /**
   * Type of breakdown to return.
   */
  breakdownType?: BreakdownType | undefined;
  /**
   * Host applications to filter by. Empty array means all host applications.
   */
  hostApplications?: Array<string> | undefined;
  /**
   * MCP tools to filter by. Empty array means all tools.
   */
  tools?: Array<string> | undefined;
  /**
   * MCP servers to filter by. Empty array means all servers.
   */
  servers?: Array<string> | undefined;
};

/** @internal */
export const BreakdownType$outboundSchema: z.ZodNativeEnum<
  typeof BreakdownType
> = z.nativeEnum(BreakdownType);

/** @internal */
export type McpBreakdownInsightsRequest$Outbound = {
  departments?: Array<string> | undefined;
  managerIds?: Array<string> | undefined;
  dayRange?: Period$Outbound | undefined;
  breakdownType?: string | undefined;
  hostApplications?: Array<string> | undefined;
  tools?: Array<string> | undefined;
  servers?: Array<string> | undefined;
};

/** @internal */
export const McpBreakdownInsightsRequest$outboundSchema: z.ZodType<
  McpBreakdownInsightsRequest$Outbound,
  z.ZodTypeDef,
  McpBreakdownInsightsRequest
> = z.object({
  departments: z.array(z.string()).optional(),
  managerIds: z.array(z.string()).optional(),
  dayRange: Period$outboundSchema.optional(),
  breakdownType: BreakdownType$outboundSchema.optional(),
  hostApplications: z.array(z.string()).optional(),
  tools: z.array(z.string()).optional(),
  servers: z.array(z.string()).optional(),
});

export function mcpBreakdownInsightsRequestToJSON(
  mcpBreakdownInsightsRequest: McpBreakdownInsightsRequest,
): string {
  return JSON.stringify(
    McpBreakdownInsightsRequest$outboundSchema.parse(
      mcpBreakdownInsightsRequest,
    ),
  );
}
