/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c1f7bf936709
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChatCitationAnnotation,
  ChatCitationAnnotation$inboundSchema,
} from "./chatcitationannotation.js";
import { ContentType, ContentType$inboundSchema } from "./contenttype.js";

export type MessageTextBlock = {
  text: string;
  type: ContentType;
  annotations?: Array<ChatCitationAnnotation> | undefined;
};

export type Message = {
  /**
   * The role of the message.
   */
  role?: string | undefined;
  /**
   * The content of the message.
   */
  content?: Array<MessageTextBlock> | undefined;
};

/** @internal */
export const MessageTextBlock$inboundSchema: z.ZodType<
  MessageTextBlock,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.string(),
  type: ContentType$inboundSchema,
  annotations: z.array(ChatCitationAnnotation$inboundSchema).optional(),
});

export function messageTextBlockFromJSON(
  jsonString: string,
): SafeParseResult<MessageTextBlock, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageTextBlock$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageTextBlock' from JSON`,
  );
}

/** @internal */
export const Message$inboundSchema: z.ZodType<Message, z.ZodTypeDef, unknown> =
  z.object({
    role: z.string().optional(),
    content: z.array(z.lazy(() => MessageTextBlock$inboundSchema)).optional(),
  });

export function messageFromJSON(
  jsonString: string,
): SafeParseResult<Message, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Message$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Message' from JSON`,
  );
}
