/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e38387a46922
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { PlatformAgent, PlatformAgent$inboundSchema } from "./platformagent.js";

export type PlatformAgentGetResponse = {
  agent: PlatformAgent;
  /**
   * Platform-generated request ID for support correlation.
   */
  request_id: string;
};

/** @internal */
export const PlatformAgentGetResponse$inboundSchema: z.ZodType<
  PlatformAgentGetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  agent: PlatformAgent$inboundSchema,
  request_id: z.string(),
});

export function platformAgentGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlatformAgentGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformAgentGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformAgentGetResponse' from JSON`,
  );
}
