/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5af2875f71af
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PlatformProblemDetailCode,
  PlatformProblemDetailCode$inboundSchema,
} from "./platformproblemdetailcode.js";
import {
  PlatformProblemDetailError,
  PlatformProblemDetailError$inboundSchema,
} from "./platformproblemdetailerror.js";

/**
 * Error response following RFC 9457, extended with `code` and `documentation_url` for machine-readable classification and self-service remediation.
 *
 * @remarks
 */
export type PlatformProblemDetail = {
  /**
   * URI identifying the error type.
   */
  type: string;
  /**
   * Short, human-readable summary of the error.
   */
  title: string;
  /**
   * HTTP status code mirrored from the response.
   */
  status: number;
  /**
   * Human-readable explanation specific to this occurrence.
   */
  detail: string;
  /**
   * Stable machine-readable error code.
   */
  code: PlatformProblemDetailCode;
  /**
   * Direct URL to documentation for this error code.
   */
  documentation_url?: string | undefined;
  /**
   * Platform-generated request ID for support correlation.
   */
  request_id: string;
  /**
   * Field-level validation problems, one entry per offending field.
   */
  errors?: Array<PlatformProblemDetailError> | undefined;
};

/** @internal */
export const PlatformProblemDetail$inboundSchema: z.ZodType<
  PlatformProblemDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string(),
  title: z.string(),
  status: z.number().int(),
  detail: z.string(),
  code: PlatformProblemDetailCode$inboundSchema,
  documentation_url: z.string().optional(),
  request_id: z.string(),
  errors: z.array(PlatformProblemDetailError$inboundSchema).optional(),
});

export function platformProblemDetailFromJSON(
  jsonString: string,
): SafeParseResult<PlatformProblemDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformProblemDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformProblemDetail' from JSON`,
  );
}
