/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1109037ce8b8
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Synchronization status after a successful refresh.
 */
export const PlatformSkillSyncResultStatus = {
  UpToDate: "UP_TO_DATE",
} as const;
/**
 * Synchronization status after a successful refresh.
 */
export type PlatformSkillSyncResultStatus = ClosedEnum<
  typeof PlatformSkillSyncResultStatus
>;

/** @internal */
export const PlatformSkillSyncResultStatus$inboundSchema: z.ZodNativeEnum<
  typeof PlatformSkillSyncResultStatus
> = z.nativeEnum(PlatformSkillSyncResultStatus);
