/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 128244b7a174
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PlatformChatCitationSnippet = {
  text: string;
  page_number?: number | null | undefined;
};

/** @internal */
export const PlatformChatCitationSnippet$inboundSchema: z.ZodType<
  PlatformChatCitationSnippet,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.string(),
  page_number: z.nullable(z.number().int()).optional(),
});

export function platformChatCitationSnippetFromJSON(
  jsonString: string,
): SafeParseResult<PlatformChatCitationSnippet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformChatCitationSnippet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformChatCitationSnippet' from JSON`,
  );
}
