/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1b403a8980ed
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PlatformSkillSourcePreviewStreamScan,
  PlatformSkillSourcePreviewStreamScan$inboundSchema,
} from "./platformskillsourcepreviewstreamscan.js";

export type PlatformSkillSourcePreviewStreamScanServerSentEvent = {
  id?: string | undefined;
  event: "SCAN";
  /**
   * Repository scan started; names every skill path found.
   */
  data: PlatformSkillSourcePreviewStreamScan;
};

/** @internal */
export const PlatformSkillSourcePreviewStreamScanServerSentEvent$inboundSchema:
  z.ZodType<
    PlatformSkillSourcePreviewStreamScanServerSentEvent,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    event: z.literal("SCAN"),
    data: z.unknown().transform((v, ctx) => {
      if (typeof v !== "string") return v;
      try {
        return JSON.parse(v);
      } catch (err) {
        ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
        return z.NEVER;
      }
    }).pipe(PlatformSkillSourcePreviewStreamScan$inboundSchema),
  });

export function platformSkillSourcePreviewStreamScanServerSentEventFromJSON(
  jsonString: string,
): SafeParseResult<
  PlatformSkillSourcePreviewStreamScanServerSentEvent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PlatformSkillSourcePreviewStreamScanServerSentEvent$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PlatformSkillSourcePreviewStreamScanServerSentEvent' from JSON`,
  );
}
