/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3239e840356d
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Current skill status.
 */
export const PlatformSkillStatus = {
  Draft: "DRAFT",
  Enabled: "ENABLED",
  Disabled: "DISABLED",
} as const;
/**
 * Current skill status.
 */
export type PlatformSkillStatus = OpenEnum<typeof PlatformSkillStatus>;

/** @internal */
export const PlatformSkillStatus$inboundSchema: z.ZodType<
  PlatformSkillStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(PlatformSkillStatus);
