/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5f9163750617
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Source category for the skill.
 */
export const PlatformSkillOrigin = {
  Custom: "CUSTOM",
} as const;
/**
 * Source category for the skill.
 */
export type PlatformSkillOrigin = ClosedEnum<typeof PlatformSkillOrigin>;

/** @internal */
export const PlatformSkillOrigin$inboundSchema: z.ZodNativeEnum<
  typeof PlatformSkillOrigin
> = z.nativeEnum(PlatformSkillOrigin);
