/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fc6cbf29ca76
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PlatformSkillVersion,
  PlatformSkillVersion$inboundSchema,
} from "./platformskillversion.js";

export type PlatformSkillVersionsListResponse = {
  /**
   * Versions available for the skill.
   */
  versions: Array<PlatformSkillVersion>;
  /**
   * Whether additional results are available.
   */
  has_more: boolean;
  /**
   * Cursor for the next page, or null when no more results are available.
   */
  next_cursor: string | null;
  /**
   * Platform-generated request ID for support correlation.
   */
  request_id: string;
};

/** @internal */
export const PlatformSkillVersionsListResponse$inboundSchema: z.ZodType<
  PlatformSkillVersionsListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  versions: z.array(PlatformSkillVersion$inboundSchema),
  has_more: z.boolean(),
  next_cursor: z.nullable(z.string()),
  request_id: z.string(),
});

export function platformSkillVersionsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlatformSkillVersionsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformSkillVersionsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformSkillVersionsListResponse' from JSON`,
  );
}
