/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5944bd48e239
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The user that another user reports to.
 */
export type PlatformUserManager = {
  /**
   * Opaque canonical Glean user ID of the manager.
   */
  user_id: string;
  /**
   * The name that Glean shows for the manager.
   */
  display_name: string;
};

/** @internal */
export const PlatformUserManager$inboundSchema: z.ZodType<
  PlatformUserManager,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_id: z.string(),
  display_name: z.string(),
});

export function platformUserManagerFromJSON(
  jsonString: string,
): SafeParseResult<PlatformUserManager, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformUserManager$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformUserManager' from JSON`,
  );
}
