/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b64d9d75e048
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PlatformTriggerEvent,
  PlatformTriggerEvent$inboundSchema,
} from "./platformtriggerevent.js";

export type PlatformTriggerEventSearchResponse = {
  /**
   * Matching events, most recent first.
   */
  results: Array<PlatformTriggerEvent>;
  /**
   * Whether more events matched than were returned. Raise `page_size` to see more; cursor-based paging is not offered yet.
   *
   * @remarks
   */
  has_more: boolean;
  /**
   * Unique identifier for this request, for support and debugging.
   */
  request_id: string;
};

/** @internal */
export const PlatformTriggerEventSearchResponse$inboundSchema: z.ZodType<
  PlatformTriggerEventSearchResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  results: z.array(PlatformTriggerEvent$inboundSchema),
  has_more: z.boolean(),
  request_id: z.string(),
});

export function platformTriggerEventSearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlatformTriggerEventSearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PlatformTriggerEventSearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformTriggerEventSearchResponse' from JSON`,
  );
}
