/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b9ffa5bb44c1
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Event type, also sent as the SSE `event` name.
 */
export const PlatformSkillSourcePreviewStreamScanType = {
  Scan: "SCAN",
} as const;
/**
 * Event type, also sent as the SSE `event` name.
 */
export type PlatformSkillSourcePreviewStreamScanType = ClosedEnum<
  typeof PlatformSkillSourcePreviewStreamScanType
>;

/**
 * Repository scan started; names every skill path found.
 */
export type PlatformSkillSourcePreviewStreamScan = {
  /**
   * Event type, also sent as the SSE `event` name.
   */
  type: PlatformSkillSourcePreviewStreamScanType;
  /**
   * Number of skill paths found in the scan.
   */
  total: number;
  /**
   * Skill paths found in the scan.
   */
  skill_paths: Array<string>;
};

/** @internal */
export const PlatformSkillSourcePreviewStreamScanType$inboundSchema:
  z.ZodNativeEnum<typeof PlatformSkillSourcePreviewStreamScanType> = z
    .nativeEnum(PlatformSkillSourcePreviewStreamScanType);

/** @internal */
export const PlatformSkillSourcePreviewStreamScan$inboundSchema: z.ZodType<
  PlatformSkillSourcePreviewStreamScan,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PlatformSkillSourcePreviewStreamScanType$inboundSchema,
  total: z.number().int(),
  skill_paths: z.array(z.string()),
});

export function platformSkillSourcePreviewStreamScanFromJSON(
  jsonString: string,
): SafeParseResult<PlatformSkillSourcePreviewStreamScan, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PlatformSkillSourcePreviewStreamScan$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformSkillSourcePreviewStreamScan' from JSON`,
  );
}
