/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a0537d504f7f
 */

import * as z from "zod/v3";
import {
  PlatformChatInputMessage,
  PlatformChatInputMessage$Outbound,
  PlatformChatInputMessage$outboundSchema,
} from "./platformchatinputmessage.js";

/**
 * Either a plain string (single user turn) or a chronological array of `USER`/`ASSISTANT` messages. The final array message must be `USER`.
 *
 * @remarks
 */
export type Input = string | Array<PlatformChatInputMessage>;

export type PlatformChatCreateRequest = {
  /**
   * Either a plain string (single user turn) or a chronological array of `USER`/`ASSISTANT` messages. The final array message must be `USER`.
   *
   * @remarks
   */
  input: string | Array<PlatformChatInputMessage>;
  /**
   * When true, respond with `text/event-stream`. When false or omitted, respond with `application/json`.
   *
   * @remarks
   */
  stream?: boolean | undefined;
  /**
   * When true (default), persist the interaction and return a `conversation_id`. When false, run ephemerally with no persistence.
   *
   * @remarks
   */
  store?: boolean | undefined;
  /**
   * Continue an existing stored conversation. Incompatible with message-array `input` and with `store: false`.
   *
   * @remarks
   */
  conversation_id?: string | undefined;
};

/** @internal */
export type Input$Outbound = string | Array<PlatformChatInputMessage$Outbound>;

/** @internal */
export const Input$outboundSchema: z.ZodType<
  Input$Outbound,
  z.ZodTypeDef,
  Input
> = z.union([z.string(), z.array(PlatformChatInputMessage$outboundSchema)]);

export function inputToJSON(input: Input): string {
  return JSON.stringify(Input$outboundSchema.parse(input));
}

/** @internal */
export type PlatformChatCreateRequest$Outbound = {
  input: string | Array<PlatformChatInputMessage$Outbound>;
  stream: boolean;
  store: boolean;
  conversation_id?: string | undefined;
};

/** @internal */
export const PlatformChatCreateRequest$outboundSchema: z.ZodType<
  PlatformChatCreateRequest$Outbound,
  z.ZodTypeDef,
  PlatformChatCreateRequest
> = z.object({
  input: z.union([
    z.string(),
    z.array(PlatformChatInputMessage$outboundSchema),
  ]),
  stream: z.boolean().default(false),
  store: z.boolean().default(true),
  conversation_id: z.string().optional(),
});

export function platformChatCreateRequestToJSON(
  platformChatCreateRequest: PlatformChatCreateRequest,
): string {
  return JSON.stringify(
    PlatformChatCreateRequest$outboundSchema.parse(platformChatCreateRequest),
  );
}
