/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 69312140acc1
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Stable machine-readable reason a discovered entry was excluded.
 */
export const PlatformSkillSourcePreviewFailureCode = {
  InvalidSkill: "INVALID_SKILL",
  SkillFetchFailed: "SKILL_FETCH_FAILED",
} as const;
/**
 * Stable machine-readable reason a discovered entry was excluded.
 */
export type PlatformSkillSourcePreviewFailureCode = OpenEnum<
  typeof PlatformSkillSourcePreviewFailureCode
>;

/** @internal */
export const PlatformSkillSourcePreviewFailureCode$inboundSchema: z.ZodType<
  PlatformSkillSourcePreviewFailureCode,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(PlatformSkillSourcePreviewFailureCode);
