/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 68103f28d594
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PlatformActionSummary,
  PlatformActionSummary$inboundSchema,
} from "./platformactionsummary.js";

export type PlatformAgentSchemasResponse = {
  /**
   * ID of the agent.
   */
  agent_id: string;
  /**
   * Name of the agent.
   */
  name?: string | undefined;
  /**
   * Agent input schema in JSON Schema format.
   */
  input_schema: { [k: string]: any };
  /**
   * Agent output schema in JSON Schema format.
   */
  output_schema: { [k: string]: any };
  /**
   * Tools that the agent can invoke, when requested.
   */
  tools?: Array<PlatformActionSummary> | undefined;
  /**
   * Platform-generated request ID for support correlation.
   */
  request_id: string;
};

/** @internal */
export const PlatformAgentSchemasResponse$inboundSchema: z.ZodType<
  PlatformAgentSchemasResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  agent_id: z.string(),
  name: z.string().optional(),
  input_schema: z.record(z.any()),
  output_schema: z.record(z.any()),
  tools: z.array(PlatformActionSummary$inboundSchema).optional(),
  request_id: z.string(),
});

export function platformAgentSchemasResponseFromJSON(
  jsonString: string,
): SafeParseResult<PlatformAgentSchemasResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformAgentSchemasResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformAgentSchemasResponse' from JSON`,
  );
}
