/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 65684ccd7f59
 */

import * as z from "zod/v3";

export type PlatformTriggerEventSearchRequest = {
  /**
   * Maximum number of events to return.
   */
  page_size?: number | undefined;
};

/** @internal */
export type PlatformTriggerEventSearchRequest$Outbound = {
  page_size: number;
};

/** @internal */
export const PlatformTriggerEventSearchRequest$outboundSchema: z.ZodType<
  PlatformTriggerEventSearchRequest$Outbound,
  z.ZodTypeDef,
  PlatformTriggerEventSearchRequest
> = z.object({
  page_size: z.number().int().default(10),
});

export function platformTriggerEventSearchRequestToJSON(
  platformTriggerEventSearchRequest: PlatformTriggerEventSearchRequest,
): string {
  return JSON.stringify(
    PlatformTriggerEventSearchRequest$outboundSchema.parse(
      platformTriggerEventSearchRequest,
    ),
  );
}
