/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4e3008c8e562
 */

import * as z from "zod/v3";
import {
  PlatformTriggerDelivery,
  PlatformTriggerDelivery$Outbound,
  PlatformTriggerDelivery$outboundSchema,
} from "./platformtriggerdelivery.js";
import {
  PlatformTriggerStatus,
  PlatformTriggerStatus$outboundSchema,
} from "./platformtriggerstatus.js";

/**
 * Partial update. Only the supplied fields are changed.
 */
export type PlatformTriggerUpdateRequest = {
  /**
   * Current trigger lifecycle state.
   */
  status?: PlatformTriggerStatus | undefined;
  /**
   * Optional note describing this trigger.
   */
  description?: string | undefined;
  /**
   * Values for the preset's inputs.
   */
  inputs?: { [k: string]: any } | undefined;
  delivery?: PlatformTriggerDelivery | undefined;
};

/** @internal */
export type PlatformTriggerUpdateRequest$Outbound = {
  status?: string | undefined;
  description?: string | undefined;
  inputs?: { [k: string]: any } | undefined;
  delivery?: PlatformTriggerDelivery$Outbound | undefined;
};

/** @internal */
export const PlatformTriggerUpdateRequest$outboundSchema: z.ZodType<
  PlatformTriggerUpdateRequest$Outbound,
  z.ZodTypeDef,
  PlatformTriggerUpdateRequest
> = z.object({
  status: PlatformTriggerStatus$outboundSchema.optional(),
  description: z.string().optional(),
  inputs: z.record(z.any()).optional(),
  delivery: PlatformTriggerDelivery$outboundSchema.optional(),
});

export function platformTriggerUpdateRequestToJSON(
  platformTriggerUpdateRequest: PlatformTriggerUpdateRequest,
): string {
  return JSON.stringify(
    PlatformTriggerUpdateRequest$outboundSchema.parse(
      platformTriggerUpdateRequest,
    ),
  );
}
