/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3a01c4a809ce
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PlatformChatCitationSnippet,
  PlatformChatCitationSnippet$inboundSchema,
} from "./platformchatcitationsnippet.js";
import {
  PlatformChatCitationSource,
  PlatformChatCitationSource$inboundSchema,
} from "./platformchatcitationsource.js";

export const PlatformChatCitationAnnotationType = {
  Citation: "citation",
} as const;
export type PlatformChatCitationAnnotationType = ClosedEnum<
  typeof PlatformChatCitationAnnotationType
>;

export type PlatformChatCitationAnnotation = {
  type: PlatformChatCitationAnnotationType;
  sources: Array<PlatformChatCitationSource>;
  start_index?: number | null | undefined;
  end_index?: number | null | undefined;
  snippets?: Array<PlatformChatCitationSnippet> | null | undefined;
};

/** @internal */
export const PlatformChatCitationAnnotationType$inboundSchema: z.ZodNativeEnum<
  typeof PlatformChatCitationAnnotationType
> = z.nativeEnum(PlatformChatCitationAnnotationType);

/** @internal */
export const PlatformChatCitationAnnotation$inboundSchema: z.ZodType<
  PlatformChatCitationAnnotation,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PlatformChatCitationAnnotationType$inboundSchema,
  sources: z.array(PlatformChatCitationSource$inboundSchema),
  start_index: z.nullable(z.number().int()).optional(),
  end_index: z.nullable(z.number().int()).optional(),
  snippets: z.nullable(z.array(PlatformChatCitationSnippet$inboundSchema))
    .optional(),
});

export function platformChatCitationAnnotationFromJSON(
  jsonString: string,
): SafeParseResult<PlatformChatCitationAnnotation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformChatCitationAnnotation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformChatCitationAnnotation' from JSON`,
  );
}
