/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4b1aaa52245c
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Supported filter operator.
 */
export const PlatformFilterOperator = {
  Equals: "EQUALS",
  NotEquals: "NOT_EQUALS",
  Gt: "GT",
  Gte: "GTE",
  Lt: "LT",
  Lte: "LTE",
} as const;
/**
 * Supported filter operator.
 */
export type PlatformFilterOperator = ClosedEnum<typeof PlatformFilterOperator>;

/** @internal */
export const PlatformFilterOperator$outboundSchema: z.ZodNativeEnum<
  typeof PlatformFilterOperator
> = z.nativeEnum(PlatformFilterOperator);
