/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6dad34f1fc6d
 */

import * as z from "zod/v3";

/**
 * Unconstrained plain-text assistant output.
 */
export type PlatformChatTextFormat = {
  /**
   * Discriminator. Must be TEXT.
   */
  type: "TEXT";
};

/** @internal */
export type PlatformChatTextFormat$Outbound = {
  type: "TEXT";
};

/** @internal */
export const PlatformChatTextFormat$outboundSchema: z.ZodType<
  PlatformChatTextFormat$Outbound,
  z.ZodTypeDef,
  PlatformChatTextFormat
> = z.object({
  type: z.literal("TEXT"),
});

export function platformChatTextFormatToJSON(
  platformChatTextFormat: PlatformChatTextFormat,
): string {
  return JSON.stringify(
    PlatformChatTextFormat$outboundSchema.parse(platformChatTextFormat),
  );
}
