/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c836031cea7d
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PlatformChatStreamResponseCompleted,
  PlatformChatStreamResponseCompleted$inboundSchema,
} from "./platformchatstreamresponsecompleted.js";

export type PlatformChatStreamResponseCompletedServerSentEvent = {
  id?: string | undefined;
  event: "RESPONSE_COMPLETED";
  data: PlatformChatStreamResponseCompleted;
};

/** @internal */
export const PlatformChatStreamResponseCompletedServerSentEvent$inboundSchema:
  z.ZodType<
    PlatformChatStreamResponseCompletedServerSentEvent,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    event: z.literal("RESPONSE_COMPLETED"),
    data: z.unknown().transform((v, ctx) => {
      if (typeof v !== "string") return v;
      try {
        return JSON.parse(v);
      } catch (err) {
        ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
        return z.NEVER;
      }
    }).pipe(PlatformChatStreamResponseCompleted$inboundSchema),
  });

export function platformChatStreamResponseCompletedServerSentEventFromJSON(
  jsonString: string,
): SafeParseResult<
  PlatformChatStreamResponseCompletedServerSentEvent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PlatformChatStreamResponseCompletedServerSentEvent$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PlatformChatStreamResponseCompletedServerSentEvent' from JSON`,
  );
}
