/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bd824a2d14c5
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PlatformChatStreamResponseFailed,
  PlatformChatStreamResponseFailed$inboundSchema,
} from "./platformchatstreamresponsefailed.js";

export type PlatformChatStreamResponseFailedServerSentEvent = {
  id?: string | undefined;
  event: "RESPONSE_FAILED";
  data: PlatformChatStreamResponseFailed;
};

/** @internal */
export const PlatformChatStreamResponseFailedServerSentEvent$inboundSchema:
  z.ZodType<
    PlatformChatStreamResponseFailedServerSentEvent,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    event: z.literal("RESPONSE_FAILED"),
    data: z.unknown().transform((v, ctx) => {
      if (typeof v !== "string") return v;
      try {
        return JSON.parse(v);
      } catch (err) {
        ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
        return z.NEVER;
      }
    }).pipe(PlatformChatStreamResponseFailed$inboundSchema),
  });

export function platformChatStreamResponseFailedServerSentEventFromJSON(
  jsonString: string,
): SafeParseResult<
  PlatformChatStreamResponseFailedServerSentEvent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PlatformChatStreamResponseFailedServerSentEvent$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PlatformChatStreamResponseFailedServerSentEvent' from JSON`,
  );
}
