/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e9a0c502793d
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PlatformSkillSourcePreviewFile,
  PlatformSkillSourcePreviewFile$inboundSchema,
} from "./platformskillsourcepreviewfile.js";

export type PlatformSkillSourcePreview = {
  /**
   * Skill name parsed from SKILL.md frontmatter.
   */
  display_name: string;
  /**
   * Skill description parsed from SKILL.md frontmatter.
   */
  description: string;
  /**
   * Resolved URL for this skill within the source.
   */
  source_url: string;
  /**
   * Commit SHA used to produce the preview.
   */
  commit_sha: string;
  /**
   * SKILL.md content fetched as part of the preview.
   */
  main_content: string;
  /**
   * Supporting files fetched with the skill.
   */
  files: Array<PlatformSkillSourcePreviewFile>;
  /**
   * Relative paths discovered for the skill.
   */
  file_tree: Array<string>;
};

/** @internal */
export const PlatformSkillSourcePreview$inboundSchema: z.ZodType<
  PlatformSkillSourcePreview,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string(),
  description: z.string(),
  source_url: z.string(),
  commit_sha: z.string(),
  main_content: z.string(),
  files: z.array(PlatformSkillSourcePreviewFile$inboundSchema),
  file_tree: z.array(z.string()),
});

export function platformSkillSourcePreviewFromJSON(
  jsonString: string,
): SafeParseResult<PlatformSkillSourcePreview, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformSkillSourcePreview$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformSkillSourcePreview' from JSON`,
  );
}
