/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 198f33194249
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PlatformSkillValidationMetadata = {
  /**
   * Skill name parsed from SKILL.md frontmatter.
   */
  display_name: string;
  /**
   * Skill description parsed from SKILL.md frontmatter.
   */
  description: string;
};

/** @internal */
export const PlatformSkillValidationMetadata$inboundSchema: z.ZodType<
  PlatformSkillValidationMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string(),
  description: z.string(),
});

export function platformSkillValidationMetadataFromJSON(
  jsonString: string,
): SafeParseResult<PlatformSkillValidationMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformSkillValidationMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformSkillValidationMetadata' from JSON`,
  );
}
