/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 30d921035e09
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PlatformChatCustomEntitySourceType = {
  CustomEntity: "custom_entity",
} as const;
export type PlatformChatCustomEntitySourceType = ClosedEnum<
  typeof PlatformChatCustomEntitySourceType
>;

export type PlatformChatCustomEntitySource = {
  type: PlatformChatCustomEntitySourceType;
  entity_id: string;
  name?: string | undefined;
  title?: string | undefined;
  url?: string | undefined;
  datasource?: string | undefined;
};

/** @internal */
export const PlatformChatCustomEntitySourceType$inboundSchema: z.ZodNativeEnum<
  typeof PlatformChatCustomEntitySourceType
> = z.nativeEnum(PlatformChatCustomEntitySourceType);

/** @internal */
export const PlatformChatCustomEntitySource$inboundSchema: z.ZodType<
  PlatformChatCustomEntitySource,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PlatformChatCustomEntitySourceType$inboundSchema,
  entity_id: z.string(),
  name: z.string().optional(),
  title: z.string().optional(),
  url: z.string().optional(),
  datasource: z.string().optional(),
});

export function platformChatCustomEntitySourceFromJSON(
  jsonString: string,
): SafeParseResult<PlatformChatCustomEntitySource, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformChatCustomEntitySource$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformChatCustomEntitySource' from JSON`,
  );
}
