/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 270a25c9c60e
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PlatformTriggerPresetInputValue = {
  /**
   * The exact value to send in the trigger's `inputs` for this choice (e.g. a channel name, a user's email, etc).
   *
   * @remarks
   */
  value: string;
  /**
   * Human-readable name for this value.
   */
  display_name: string;
};

/** @internal */
export const PlatformTriggerPresetInputValue$inboundSchema: z.ZodType<
  PlatformTriggerPresetInputValue,
  z.ZodTypeDef,
  unknown
> = z.object({
  value: z.string(),
  display_name: z.string(),
});

export function platformTriggerPresetInputValueFromJSON(
  jsonString: string,
): SafeParseResult<PlatformTriggerPresetInputValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformTriggerPresetInputValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformTriggerPresetInputValue' from JSON`,
  );
}
