/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 9d74b88c203a
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Type of the section. This defines how the section should be interpreted and rendered in the digest.
 */
export const SectionType = {
  /**
   * A standard section for channel-based digests (e.g. from Slack, Teams).
   */
  Channel: "CHANNEL",
  /**
   * A dedicated section that surfaces user mentions (actionable, informative, or all).
   */
  Mentions: "MENTIONS",
  /**
   * A section driven by a generic topic, not tied to any specific channel or instance.
   */
  Topic: "TOPIC",
} as const;
/**
 * Type of the section. This defines how the section should be interpreted and rendered in the digest.
 */
export type SectionType = OpenEnum<typeof SectionType>;

/** @internal */
export const SectionType$inboundSchema: z.ZodType<
  SectionType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(SectionType);
