/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6e056d0be7fa
 */

import * as z from "zod/v3";

export type SeenFeedbackInfo = {
  /**
   * The confidence of the user seeing the object is high because they explicitly interacted with it e.g. answer impression in SERP with additional user interaction.
   */
  isExplicit?: boolean | undefined;
};

/** @internal */
export type SeenFeedbackInfo$Outbound = {
  isExplicit?: boolean | undefined;
};

/** @internal */
export const SeenFeedbackInfo$outboundSchema: z.ZodType<
  SeenFeedbackInfo$Outbound,
  z.ZodTypeDef,
  SeenFeedbackInfo
> = z.object({
  isExplicit: z.boolean().optional(),
});

export function seenFeedbackInfoToJSON(
  seenFeedbackInfo: SeenFeedbackInfo,
): string {
  return JSON.stringify(
    SeenFeedbackInfo$outboundSchema.parse(seenFeedbackInfo),
  );
}
