/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ShortcutErrorErrorType = {
  NoPermission: "NO_PERMISSION",
  InvalidId: "INVALID_ID",
  ExistingShortcut: "EXISTING_SHORTCUT",
  InvalidChars: "INVALID_CHARS",
} as const;
export type ShortcutErrorErrorType = ClosedEnum<typeof ShortcutErrorErrorType>;

export type ShortcutError = {
  errorType?: ShortcutErrorErrorType | undefined;
};

/** @internal */
export const ShortcutErrorErrorType$inboundSchema: z.ZodNativeEnum<
  typeof ShortcutErrorErrorType
> = z.nativeEnum(ShortcutErrorErrorType);

/** @internal */
export const ShortcutError$inboundSchema: z.ZodType<
  ShortcutError,
  z.ZodTypeDef,
  unknown
> = z.object({
  errorType: ShortcutErrorErrorType$inboundSchema.optional(),
});

export function shortcutErrorFromJSON(
  jsonString: string,
): SafeParseResult<ShortcutError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShortcutError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShortcutError' from JSON`,
  );
}
