/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e0274c664fba
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Success response for custom metadata operations
 */
export type SuccessResponse = {
  /**
   * Indicates if the operation was successful
   */
  success: boolean;
};

/** @internal */
export const SuccessResponse$inboundSchema: z.ZodType<
  SuccessResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().default(true),
});

export function successResponseFromJSON(
  jsonString: string,
): SafeParseResult<SuccessResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SuccessResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SuccessResponse' from JSON`,
  );
}
