/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ToolsCallParameter,
  ToolsCallParameter$Outbound,
  ToolsCallParameter$outboundSchema,
} from "./toolscallparameter.js";

export type ToolsCallRequest = {
  /**
   * Required name of the tool to execute
   */
  name: string;
  /**
   * The parameters for the tool. Each key is the name of the parameter and the value is the parameter object.
   */
  parameters: { [k: string]: ToolsCallParameter };
};

/** @internal */
export type ToolsCallRequest$Outbound = {
  name: string;
  parameters: { [k: string]: ToolsCallParameter$Outbound };
};

/** @internal */
export const ToolsCallRequest$outboundSchema: z.ZodType<
  ToolsCallRequest$Outbound,
  z.ZodTypeDef,
  ToolsCallRequest
> = z.object({
  name: z.string(),
  parameters: z.record(ToolsCallParameter$outboundSchema),
});

export function toolsCallRequestToJSON(
  toolsCallRequest: ToolsCallRequest,
): string {
  return JSON.stringify(
    ToolsCallRequest$outboundSchema.parse(toolsCallRequest),
  );
}
