/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c3daceb26669
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { UgcType, UgcType$inboundSchema } from "./ugctype.js";

export type UgcAction = {
  create: UgcType;
};

/**
 * An action to perform on user-generated content. This may be accompanied by `text` on the ChatMessageFragment, which acts as the display name content of the pill.
 */
export type UgcActionUnion = UgcAction;

/** @internal */
export const UgcAction$inboundSchema: z.ZodType<
  UgcAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  create: UgcType$inboundSchema,
});

export function ugcActionFromJSON(
  jsonString: string,
): SafeParseResult<UgcAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UgcAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UgcAction' from JSON`,
  );
}

/** @internal */
export const UgcActionUnion$inboundSchema: z.ZodType<
  UgcActionUnion,
  z.ZodTypeDef,
  unknown
> = z.lazy(() => UgcAction$inboundSchema);

export function ugcActionUnionFromJSON(
  jsonString: string,
): SafeParseResult<UgcActionUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UgcActionUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UgcActionUnion' from JSON`,
  );
}
