/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * A user's role with respect to a specific document.
 */
export const UserRole = {
  Owner: "OWNER",
  Viewer: "VIEWER",
  AnswerModerator: "ANSWER_MODERATOR",
  Editor: "EDITOR",
  Verifier: "VERIFIER",
} as const;
/**
 * A user's role with respect to a specific document.
 */
export type UserRole = ClosedEnum<typeof UserRole>;

/** @internal */
export const UserRole$inboundSchema: z.ZodNativeEnum<typeof UserRole> = z
  .nativeEnum(UserRole);
/** @internal */
export const UserRole$outboundSchema: z.ZodNativeEnum<typeof UserRole> =
  UserRole$inboundSchema;
